### ISSUE TITLE
1.5 汉化召集

### ISSUE THREAD

**Issue by cloudwu** [cloudwu/stellaris_cn#102]
这次文本量巨大啊。具体见 https://github.com/cloudwu/stellaris_cn/commit/5578cd8484177ae57181684ab42a2c4543b44832

大家商量一下怎么搞？

**Comment by inkitter** [comment]
①整个文件的：
achievements 111
modifiers_utpia 51
musicplayer  57
script_loc 24
traditions 342
unrest 132
utpopia_ascension 527
utopia 235
utopia_megastructures 256


②行数不多的：
dip_messages
events_2
events_5
event_chains
guardian
messages
modifiers_2
triggers
tutorial
events
technology  （似乎目前缺几行新增的英文，我还没做PR，别的文件缺行的地方都用PR补上了了。0407 16:03）


③词汇需要琢磨，比较困难的：
l_english
modifiers
pop_factions

**Comment by cloudwu** [comment]
整文件的可以计划排在后面。要不先把行数不多的先搞定。

**Comment by cloudwu** [comment]
如果有计划翻译大块文本，不想立刻提 pr 的同学，可以在这个贴下留言。注明正在做哪一块的工作，避免重复劳动。

**Comment by cloudwu** [comment]
我今天的感觉是，第一优先级是翻译主界面，游戏中最常见的词句。

大家可以先自己玩玩，翻译那些最影响理解游戏概念的部分。

**Comment by Tianchenglipu** [comment]
我在翻译AP的部分，不要和我重复了= =
目前我把所有的AP名字都翻译成了四字的

**Comment by yaxu75** [comment]
从别处看到这里的汉化，希望能帮忙，能否麻烦邀请我？

**Comment by yaxu75** [comment]
从别处看到这里的汉化，希望能帮忙

**Comment by yaxu75** [comment]
achievements 我做完了，比较奇怪的是没有1.5新加的成就。
目前在着手做utopia_megastructures

**Comment by Tomek9587** [comment]
刚刚做完modifiers_utopia_l_english

**Comment by cloudwu** [comment]
做一部分就记得提交 pr ，不要分支太久。

**Comment by xd845217xd** [comment]
我在Steam上看到了您的翻譯計劃，目前正在翻譯"Unrest"的部分，希望能貢獻一己之力！

**Comment by cloudwu** [comment]
@soarqin @mrgump @winnersun @mengxy @441707521 @zsc19921016 @yuan1238y  强行拉人。

**Comment by mengxy** [comment]
啊，被点名了，还在玩儿 eu4 的 MoH，云风大大这是逼我先玩儿 Utopia 的节奏啊...

**Comment by zsc19921016** [comment]
Utopia没买。。我挑几个文本少的，guardian,messages和events，只有几十行的DLC内容

**Comment by winnersun** [comment]
又要开始了吗？有什么难度适中的可以交给我

发自我的 iPhone

在 2017年4月11日，13:49，云风 <notifications@github.com<mailto:notifications@github.com>> 写道：


@soarqin<https://github.com/soarqin> @mrgump<https://github.com/mrgump> @winnersun<https://github.com/winnersun> @mengxy<https://github.com/mengxy> @441707521<https://github.com/441707521> @zsc19921016<https://github.com/zsc19921016> @yuan1238y<https://github.com/yuan1238y> 强行拉人。

**Comment by soarqin** [comment]
买了一直没空玩，我先看一下待翻译的文本，和游戏更新对照一下

**Comment by mrgump** [comment]
刚买了一份1.5.0版本，最近抽时间先玩玩。

2017-04-12 2:20 GMT+08:00 Soar Qin <notifications@github.com>:

**Comment by inkitter** [comment]
整理了一下剩余部分，见沙发。
1.5更新时有些英文有所变化，我之前做的翻译工具可以对比新旧差异，已翻译完成的部分可以针对这部分修正下。[#92](https://github.com/cloudwu/stellaris_cn/issues/92)

**Comment by huangjua** [comment]
你好，楼主，先谢谢诸位的辛勤劳动~由于在STEAM那边我无法留言，所以在这里跟你反馈，

**Comment by huangjua** [comment]
如果开启教程，会发现，施工船在教程里面的字眼是工程船~望改一下，强迫症感激不尽~

**Comment by cloudwu** [comment]
@huangjua 每个人都可以改的，你可以替换一下，然后提个 pr ，我会合并。

**Comment by huangjua** [comment]
好的，我看一下怎么替换？

**Comment by cloudwu** [comment]
多多参于，随手翻译还没有翻的条目 :)
