### ISSUE TITLE
类人机器人？？？

### ISSUE THREAD

**Issue by Tianchenglipu** [cloudwu/stellaris_cn#120]
很容易想到的翻译——智能人听起来很奇怪，因为里面没有任何地方表示它是机器人。

类人机器人感觉也很古怪，名字里有两个“人”字。而且会让人感到困惑，因为形状上更接近人怎么会让它更加高级。因为“类人”这个词语人的第一感想是形状上类人。

我认为游戏想告诉我们的是，机器人是没有智能的机器人，droids是拥有初步智能的机器人，synthetics是拥有完全能匹敌有机智能生物的智能的机器人。这样的话，我认为把droid的“类人”一义解释为“就快要像人一样聪明了”会比较好。也就是将它翻译为“智能机器人”。

写机器人的话，五个汉字我个人感觉有点太长，但是这不重要。synthetics是一个生造的词语，就算不叫他“合成机器人”也是可以的。

顺便一提的是，“机器人”这个约定俗成的叫法是由于人们认为“这是一个机器做的，长得像人的东西”，这是一个彻底的误解，机器人从来不需要是人形的，尤其是看到某些日本动画片的观众将有人驾驶的人形载具叫作机器人的时候更是令人痛心疾首。但是语言习惯已经定型，而且抛开机器人这个名字，我也想不到一个好译法来翻译Robot。

**Comment by Tianchenglipu** [comment]
@cloudwu  如果你同意的话，我就开始批量了。

**Comment by cloudwu** [comment]
(an)droid 就是外形上更像人类的 robot 啊。https://www.quora.com/What-is-the-difference-between-a-robot-and-a-droid

**Comment by Tianchenglipu** [comment]
可是不是人型生物的robot为什么也会是人形体呢？

**Comment by cloudwu** [comment]
robot 机器感更强一些, 比如外表更金属感。 robot 可以像人，也可以不像。

droid 一定是人形的，比 robot 更像人。
http://www.techrepublic.com/blog/geekend/the-difference-between-robots-and-androids/

**Comment by cloudwu** [comment]
我已经全部替换成智能人。

**Comment by Tianchenglipu** [comment]
推荐叫智能朲，既是智能人的读音，又可以表示不是个有机体 =。=

**Comment by cloudwu** [comment]
不要用生僻字。字体未必支持，可以运行脚本查看支持情况。

**Comment by Tianchenglipu** [comment]
哈哈哈，我是开玩笑的 →_→
