### ISSUE TITLE
贴吧汉化

### ISSUE THREAD

**Issue by soarqin** [cloudwu/stellaris_cn#15]
http://tieba.baidu.com/p/4831990001
http://steamcommunity.com/sharedfiles/filedetails/?id=683409704

我自己写了个脚本对比了下，贴吧汉化了绝大多数1.3.0新加的字符串，不知道借用是否有版权问题，是否可以直接把没翻译的条目直接先拉过来再慢慢修订

**Comment by 441707521** [comment]
围观

**Comment by cloudwu** [comment]
注明一下没问题吧，原本很多也是 3dm 的。

是否可以先把  guardians 有关的整个文件先复制过来，其它的少量的可以自己翻译。最大头的 `l_english` 已经翻译完了。

拿过来应该也需要核对翻译用词，可能有不一样的地方。

另外 `l_english` 里有几处和 guardians 有关的名词，我都留着没有翻译。

总体上，我想操作上可以慢慢进行，小心避免合并出现错误。

**Comment by cloudwu** [comment]
我看了一下，除了 guardians 是个大头，和我今天搞完的 `l_english` 主文件相当外，其它文件改动的总和还不到今天我的工作多。

那些零碎的活应该不需要从中挑出来合并了。

可以直接在 github 上用 blame 查看 1.3 每个改动文件具体修改的位置。

**Comment by cloudwu** [comment]
看了一下版权声明：
```
* 群星 (Stellaris)本体由Paradox Interactive游戏公司开发并保有版权。本汉化包版权由Stellaris贴吧汉化组制作所有，严禁在未经授权的情况下以任何形式在任何平台上转载、上传。
```
既然不让就算了。

**Comment by soarqin** [comment]
不过这个说是禁止转载，如果只是合并部分条目，不知道从各种意义上是否算转载

**Comment by cloudwu** [comment]
不急的话，可以先慢慢搞。我估计下个周末可以把  guardians (DLC) 之外的所有部分补全了。
目前我是自己慢慢打一盘，碰到的所有文本顺便校对。过去的文本有很多地方有问题。

**Comment by soarqin** [comment]
有些很难碰到，我之前打了半盘，然后看文本，发现很多没翻译的地方根本没碰到，好多触发的几率都不高

**Comment by soarqin** [comment]
[others.txt](https://github.com/cloudwu/stellaris_cn/files/546460/others.txt)
[guardian.txt](https://github.com/cloudwu/stellaris_cn/files/546461/guardian.txt)
我用脚本对比了生成了替换文件，然后整理去掉了一些不需要改的东西，采纳了一些名词修正
others.txt是guardian之外其他所有文件的替换
替换文件格式是yaml，很容易看懂

**Comment by soarqin** [comment]
部分工作见 #17

**Comment by cloudwu** [comment]
我今天翻译了利维坦的一小段，对比贴吧版本，我还是比较喜欢自己翻的。

比如：

"The discovery of a giant monstrosity living in the void has made the [Root.GetName] appear all the more insignificant in the grand scheme of things. The first creature our proud empire encounters might just be its last. The leviathan's image has spread across the empire, causing mass hysteria and pleas for action.\n\nOur fleet's report stated that the beast appears powerful enough to crush even the most capable armada, and recommends caution."

贴吧版本是

我们发现了一个生活于虚空之中的庞大怪物，它庞大的身躯使得[Root.GetName]任何伟大的工程都显得微不足道。这可能是我们骄傲的帝国遇到的第一个，亦或是最后一个。发现利维坦的消息以及其图像已经迅速传遍整个帝国各地， 造成了帝国内部大规模对其发动攻击的请求。\n\n根据我们舰队发来的情报，这头巨兽十分强大，甚至可以轻而易举的碾碎全河系最强的舰队，我们应该就是否对他发动攻击进行进一步讨论。

我的版本是

虚空中出现了一只巨大怪兽，在它的巨大身形之下，[Root.GetName]的一切都看起来微不足道。在我们帝国曾遭遇的生物中，它空前绝后。利维坦的影像迅速传遍了帝国，造成了巨大的恐慌，到处是要求发动攻击的声音。\n\n根据舰队报告，这只怪兽威力巨大，即使最强舰队出击恐怕也无法摧毁它，必须小心对待。

"The [Root.GetSpeciesAdj] populace is praying. The giant being encountered in the dark has caused many a denizen of the empire to fear for their sanity, or doubt their faith in the divine. Are these giants the guardians of all life and that which created it, or its enemy?"

贴吧版本是

[Root.GetSpeciesAdj]的民众开始祈祷。在黑暗宇宙中现身的庞然大物开始使他们感到极其恐惧，甚至开始质疑他们神圣的信仰。这些巨型生物到底是造世主赐予全宇宙的守护者，还是伟大造世主的敌人呢？

我的版本是

[Root.GetSpeciesAdj]民众在祈祷。暗影中的巨兽带来的恐惧直击帝国人民的心灵，许多人开始质疑神圣的信仰。这些巨兽到底是芸芸众生的守护者，还是敌人？

"The [Root.GetName] has encountered something that is beyond sublime. Giant beings, their sheer existence a testament to the unfathomable wonders of the universe, that make most lifeforms appear like flickering lights next to burning stars.\n\nDespite the true nature of the leviathan being unknown, the people on [Root.Capital.GetName] are hopefully in awe of what has been found, and optimistic about what it may bring."

贴吧版本是

[Root.GetName]遇到了一个超越一切存在的谜一样的物体。一个可怕的庞然大物，他们纯粹的存在证明了宇宙一直在创造着难以估量的奇迹，他们使得大量生命形式看起来像是闪耀恒星旁的一只萤火虫。\n\n尽管利维坦的消息真实与否还未曾可知，但[Root.Capital.GetName]的人们仍然希望我们对这个存在心存敬畏， 并很乐观这个存在将为我们带来很多可以帮助我们的东西。

我的版本是

[Root.GetName]遭遇之物叹为观止。这些巨型生物的存在昭示着浩瀚宇宙的神秘莫测，所有的生命形式在它面前就像是恒星边的一点荧光。\n\n尽管利维坦的本质是什么尚未知晓，但[Root.Capital.GetName]上的人们对之充满敬畏，期待着它能带来些什么。

"We have now found beings far surpassing anything encountered in our empire's spacefaring history. Life capable of growing to an unprecedented scale, rivaling moons in size and mass.\n\nNothing could have prepared us for this. This day will forever mark a turning point in the story of the [Root.GetName]. Let us hope we survive long enough to tell it."

贴吧版本是

我们现在发现的生命体是自从我们的帝国踏入太空以来其闻所未闻见所未见的。这个生命成长到了前所未有的规模，在尺寸和质量上足以匹敌一颗卫星。\n\n我们没有为这一切做好准备。这一天将是[Root.GetName]历史的一个转折点。希望我们可以生存足够长的时间去了解这个存在。

我的版本是

我们发现这个生物在帝国太空史上独一无二。生物居然可以长得如此之大，堪比月亮的质量与体积。\n\n对这个家伙，我们做任何准备都没有意义。今天将是[Root.GetName]的历史转折点。希望我们可以活得足够长将它载入历史。"

"News of a giant being seen in the dark void of space is spreading across the empire like a plague. There is concern and optimistic wonder, but mostly brings an existential dread to the populace. Historical documents will record this day as one of tremendous importance."

贴吧版本是

在虚空之中发现庞大怪物的新闻就像瘟疫一样在我们的帝国中传播。有一些关注者对此表示乐观，但是还是导致了民众的大规模恐慌。无论这个怪物会带来什么，这一天都这将作为我们历史中最重要的一天之一记载在我们的史书中。

我的版本是

在黑暗虚空中遇见巨兽的消息如瘟疫般席卷整个帝国。无论悲观还是乐观，都无疑给民众带来了巨大的焦虑。历史文献将赋予今天一个历史上的特殊地位。

* Is this darkness all that exists?
* We are but motes of dust.
* It is awe-inspiring.

贴吧版本是

* 这个存在是否是真实的呢？ 
* 我们只是宇宙中的尘埃罢了。
* 这真是令人敬畏的存在。

我的版本是

* 这黑暗就是全部了吗？
* 我们不过是浩瀚宇宙中的几粒尘埃。
* 叹为观止。

**Comment by soarqin** [comment]
@cloudwu 嗯，从翻译角度来说的话，自己慢慢润色肯定是最好的，所以可以先拉过来再修，应该比自己从头翻译效率要高，而且也不比过度追求辞藻，重要的是通顺，毕竟不是官方汉化，不必太强迫症
剩下4个文件未润色的分支在这里: https://github.com/soarqin/stellaris_cn/tree/unpolished

**Comment by cloudwu** [comment]
不是润色的问题，我觉得是有些地方翻译的不对。中文说的有点别扭。而看译文修的效率比看原文翻的效率低很多。

**Comment by soarqin** [comment]
@cloudwu 我是用vimdiff左边开英文右边开中文来翻译的，所以对比起中英文来很方便

**Comment by cloudwu** [comment]
blame 主要是用来检查哪里有漏掉的翻译。如果 blame 上写的是 update 1.3 的话，说明是在 1.3 更新的时候从英文文件合并过来的条目。如果有翻译，会变成后续的 commits.

**Comment by soarqin** [comment]
对剩下这几个文件blame用处不大，没翻译的都是成块的，一眼就看出来了，而且1.2也有一些没翻译的或者需要润色的，之前我统一翻译和对比贴吧的时候碰到了几个顺手搞掉了
