### ISSUE TITLE
关于Stagnant Ascendancy的翻译问题

### ISSUE THREAD

**Issue by yaxu75** [cloudwu/stellaris_cn#173]
Stagnant Ascendancy原译为“停滞的优越国”，在164＃里被我修改为了“停滞帝国”，附带的其他修改详情见https://github.com/cloudwu/stellaris_cn/pull/164/commits/2453f1196a2e4ca2f7db24e9d0755fda59dde16a
修改的原因是老版本并没有civic特质，新版本加了civic特质后原来的一些翻译“昏睡的督导国“，”衰落的帝国“和新版本civic风格不是很搭，主要在于新版本的civic都没有“的”字。所以我就把附带的翻译中“的”字都删掉了
所有相应更改都在164＃里，如果大家觉得原来比较好可以改回去。

**Comment by Tianchenglipu** [comment]
的字无所谓啊。还以为你会对优越国的部分有意见。

帝国的译法我是不同意的，因为这个游戏里全是帝国，帝国这个词没有特别的高贵性。

如果一定要去掉的字并压缩成两个字，就叫停滞上国、觉醒上国吧。

至于昏睡的督导国，昏睡先导可以接受。

**Comment by Tianchenglipu** [comment]
另外你改的是两个最不重要的地方，那是1.4里的政府

**Comment by Tianchenglipu** [comment]
等会我就发一个pull

**Comment by yaxu75** [comment]
是的，因为1.5里的新civic已经都汉化了，1.4里堕落帝国原本不是civic的属性现在被重新设置成了堕落帝国的civic，所以大概才出现了游戏里同一个地方风格不太一样的问题
下次修改老文档前我会先问问大家的意见

**Comment by yaxu75** [comment]
“上国”确实是比“帝国”更加精准的翻译

**Comment by Tianchenglipu** [comment]
#174 发完了

**Comment by cloudwu** [comment]
天朝上国么  :)

**Comment by Tianchenglipu** [comment]
嗯，对对对 :)
