### ISSUE TITLE
食物出口196/70 bug?

### ISSUE THREAD

**Issue by cloudwu** [cloudwu/stellaris_cn#176]
steam mod 页面有两人反应

> 一加国教崇拜，政体立刻变食物出口196/70

> 选择帝国那里 勇达里母王国的制度怎么是“食物出口(196/70)”。。。

但是我这里无法重现？是否还有人遇到了同样的问题？

**Comment by inkitter** [comment]
既没有“食物出口”，也没有"出口"这个独立的词。所以即使是自动组合在一起的词也不应该出现这种现象。
应该是开了别的什么mod导致的。
有几个食物交易的mod。
还有一个用于mod汉化的more chinese项目，那个项目里文本非常多，可能会有影响。不过现在那个是别人在做，具体里面有什么就不太清楚了。

**Comment by wwssaa** [comment]
看着像那个殖民地食物进出口的mod
我记得more chinese里面没有这个mod，只有civilian trade，然而那个也没食物进出口功能
也可能是老mod被错误引用了
