### ISSUE TITLE
megastructure 的翻译

### ISSUE THREAD

**Issue by cloudwu** [cloudwu/stellaris_cn#177]
目前 megastructure 是翻译成 巨型结构 , 这个是 wikipedia 上的直译法。
https://zh.wikipedia.org/wiki/%E5%B7%A8%E5%9E%8B%E7%BB%93%E6%9E%84

但是我个人觉得太生硬，不符合传统汉语的表述。

我比较喜欢的译法是：

工程奇观 或 建筑奇观。

**Comment by Tianchenglipu** [comment]
mega虽然是个数量级，但英语游戏用的多了，就逐渐引申成了super的近义词。所以最开始我想的是超级工程。

如果我有提交过涉及到megastructure的翻译文本的话，我应该都是翻译成巨型建筑的。

**Comment by cloudwu** [comment]
mega- 的词源是 megalo- , 是 large ,great, grand , abnormally large 的意思。然后被引申为一百万。

比如 megalopolis 大都会。

其中暗含了伟大（褒义）的意思。

目前文本里有 巨型建筑和矩形结构两种译法，需要统一。

**Comment by Tianchenglipu** [comment]
我还不知道这种事情……

让我选肯定是巨型建筑。

奇观虽然很游戏，但是奇观一共就没几种，而且轨道栖所也是算巨型建筑的，轨道栖所这种廉价的巨型建筑就不太适合叫作奇观。

此外，叫奇观还有一个不好，那就是建造奇观所要的AP就叫银河奇观……

**Comment by Tianchenglipu** [comment]
我还不知道这种事情……

让我选肯定是巨型建筑。

奇观虽然很游戏，但是奇观一共就没几种，而且轨道栖所也是算巨型建筑的，轨道栖所这种廉价的巨型建筑就不太适合叫作奇观。

此外，叫奇观还有一个不好，那就是建造奇观所要的AP就叫银河奇观……

**Comment by cloudwu** [comment]
"建筑" 在中文中比较难联想到环世界这种规模的东西。

**Comment by Tianchenglipu** [comment]
哇靠，手机抽了，而且手机不能删除重复的回复……

**Comment by Tianchenglipu** [comment]
巨型设施呢？还不行就只能去通俗化了。

**Comment by cloudwu** [comment]
奇观不好的地方在于，游戏里有了 wonder 这个概念了。不过，异形动物园 轨道栖所 乐土园 这些还真都是归在 wonders 下面的。

**Comment by cloudwu** [comment]
如果实在想找个专有名词，可能巨型结构还是 还是比较合适的。 可能只是我平常见的少。

**Comment by Tianchenglipu** [comment]
虽然我们嘴皮上说巨型设施，但是其规模之巨大，是超出我们日常生活的理解的。我们与天文数字打交道并不多，所以对于吹上天的数量级本就缺乏共鸣。举例来说，建造一个戴森球，在现实中，假设2000矿物能造一个2km的战舰，不停打minerals 1000000的秘籍打到人体寿命耗尽都是凑不足戴森球的材料的。但是因为这与我们的日常生活相距甚远，要找个词语兼顾着传达这层含义是不可能的。不如舍弃它，追求通俗。

**Comment by Tianchenglipu** [comment]
见得少说明它不通俗。megastrucure，无论是mega还是structure都很通俗，直译的话最合适的就是巨型建筑或者类似的。把structure翻译成建筑、设施都是可以的，但是在明知道这是一种建筑的情况下翻译成结构，我就觉得很像谷歌翻译，因为谷歌翻译不能做到智能场合判断。

**Comment by cloudwu** [comment]
在这个游戏里，"建筑" 还是用的很多的，多用于翻译 building 了，就是在星球表面建造的东西。选词主要还是方面玩的时候有区分度。

**Comment by cloudwu** [comment]
另外，巨型结构并不是机器翻译。是一个专有名词，特制戴森环这些东西的。只是平常用的比较少罢了。

**Comment by cloudwu** [comment]
https://www.tipelse.com/article/298688.html
http://www.guokr.com/article/172398/

在谈及戴森球的时候都回避用建筑这个词。

**Comment by Tianchenglipu** [comment]
居然连这个专有名词都有，我还以为没有的

**Comment by cloudwu** [comment]
我查了一下，目前翻译不统一，不只两种，还有地方翻译成巨型工程 
https://github.com/cloudwu/stellaris_cn/blob/master/cn/localisation/english/modifiers_utopia_l_english.yml#L2 

如果巨型结构比较生疏，是不是可以考虑 巨型天体结构 或者 天体结构。

**Comment by Tianchenglipu** [comment]
那叫设施怎样？因为你讲戴森球和环是『结构』我是服的，很有天方夜谭的感觉，但是轨道栖所这种……就比较麻烦，因为它不是一个天方夜谭，它是这个游戏里最小的巨型结构，巨型是相对于地表上那些玩具而言。你叫它『巨型结构』，我觉得有点大炮打蚊子的感觉。

**Comment by inkitter** [comment]
我觉得用便于了解的词比较好。比如看到 `巨型结构` 去查，至少在维基上能够查到戴森球、宇宙殖民地。
通俗一些，有翻译成 `超级建筑` 的。
学术上表述megastructure时可能用到： `巨型建筑` `巨构建筑` 。
[CNKI-megastructure](http://xuewen.cnki.net/R2006111170002243.html)

既然已有很多翻译方法，也不应该去创造新的了。

**Comment by Tianchenglipu** [comment]
我觉得不如叫面子工程。因为你想一想，花费这样多的矿物就是为了个每月+400能量，吹上天的科研枢纽才每项加50，妥妥的面子工程。 →_→

**Comment by cloudwu** [comment]
先统一成巨型结构吧。我来搞。

**Comment by Tianchenglipu** [comment]
别别，先别急着替换，我在翻译这一块= =

**Comment by inkitter** [comment]
润色最后吧，记录一下需要统一的几个词。

**Comment by cloudwu** [comment]
我替换完了。要活用 git merge 啊。软件会帮你合并。

**Comment by cloudwu** [comment]
千万别 pull 下来拷贝粘贴回去了。大部分merge 软件都会自动做的，少量冲突手工比对就好了。我只改了名词，没有修饰翻译。

**Comment by Tianchenglipu** [comment]
告诉你们一个秘密，法令延时+X%对宣为圣地的法令也有效:)

**Comment by soarqin** [comment]
如果是中文表达，可能巨型人工结构好一点吧，从意思上区分于一些自然形成的巨型结构

**Comment by rexunil** [comment]
‘宏构’ 简单有力

**Comment by 6XH** [comment]
超级工程？
