### ISSUE TITLE
happiness的翻译

### ISSUE THREAD

**Issue by Tianchenglipu** [cloudwu/stellaris_cn#178]
我认为人口的happiness和派系的happiness应该写成两种。因为作为一个派系，对国家提要求，却谈“幸福度”，有点太古怪了。

我推荐人口的happiness叫幸福度，派系的happiness叫满意度。

**Comment by cloudwu** [comment]
我认为没问题。不过不该似乎也没问题。或许是 幸福度的 度有点违和。叫 幸福感 就亲切一些。

**Comment by Tianchenglipu** [comment]
派系提的issue翻译成问题有点不太好的感觉，叫诉求比较符合直觉。因为issue是他们认为这算是一个问题，但对玩家就不一定。例如平等主义的派系认为专制统治是一个问题，玩家并不这么觉得。

**Comment by cloudwu** [comment]
issue 怎么被翻译成问题了？我记得我翻译成 议题 的。

**Comment by Tianchenglipu** [comment]
哈哈哈哈哈

**Comment by Tianchenglipu** [comment]
呃，刚才看了一下，文本还是议题，那是我大脑错乱了= =

**Comment by yaxu75** [comment]
派系的happiness实际上是该派系人口未受修正的基本happiness，翻译成“派系人口幸福度”应该是最精确的，但是太过繁琐了…

**Comment by soarqin** [comment]
派系的happiness本质上就是该派系对国家统治的合作满意度，选一个合适的词的话，我提一个建议是翻译为: 认同感/认同度
