### ISSUE TITLE
events_2_l_english 文件缺最后一块翻译，有无志愿者认领

### ISSUE THREAD

**Issue by cloudwu** [cloudwu/stellaris_cn#18]
events 2 里面新增的一些事件已经翻译完毕。最后还差一大块。

https://github.com/cloudwu/stellaris_cn/blob/master/cn/localisation/events_2_l_english.yml#L1417-L1561

看看有无同学愿意认领翻译？

**Comment by StefanZeng** [comment]
mark
晚上翻译

**Comment by cloudwu** [comment]
这块任务拆分成两部分可能好点。

堕落帝国部分

https://github.com/cloudwu/stellaris_cn/blob/master/cn/localisation/events_2_l_english.yml#L1426-L1492

觉醒帝国 天国之战部分

https://github.com/cloudwu/stellaris_cn/blob/master/cn/localisation/events_2_l_english.yml#L1501-L1561

@StefanZeng 翻译的怎样了？

**Comment by cloudwu** [comment]
@StefanZeng 刚才看到在你的仓库里已经翻译完了。提个 pr 过来大家讨论吧。

**Comment by StefanZeng** [comment]
@cloudwu 好的。晚一点吹了

**Comment by cloudwu** [comment]
还差几句，加油 :)

**Comment by cloudwu** [comment]
League of Non-Aligned Powers 我最终定下来翻译成  不结盟力量联合体 。现在相关的段落已经翻译完了。 https://github.com/cloudwu/stellaris_cn/commit/897ce8482abdc229cc96df409f103f5fc987ba23

ps. 不要只翻译标题或短句子。因为往往这些都是依据 desc 的长段落读完了才能决定真正的意思的。所以最好在翻译时都是围绕一个完整的段落进行。
