### ISSUE TITLE
dip_messages_l_english.yml 中关于外交辞令部分

### ISSUE THREAD

**Issue by cloudwu** [cloudwu/stellaris_cn#19]
https://github.com/cloudwu/stellaris_cn/blob/master/cn/localisation/dip_messages_l_english.yml#L1138-L1195

这部分尚无人认领，同学们报名 :)

注意：术语请参照 https://github.com/cloudwu/stellaris_cn/pull/13 这里讨论最后达成的结果。翻译同时可以对照  https://github.com/cloudwu/stellaris_cn/blob/master/cn/localisation/l_english.yml#L4881-L4926 等外交对话。

**Comment by soarqin** [comment]
明天晚上开始有空，如果到明晚没人领我再来领
