### ISSUE TITLE
guardian_l_english 任务分配

### ISSUE THREAD

**Issue by cloudwu** [cloudwu/stellaris_cn#20]
https://github.com/cloudwu/stellaris_cn/blob/master/cn/localisation/guardian_l_english.yml

利维坦相关文本数量很多。想参加翻译的同学可以回帖认领其中的一部分。

**Comment by cloudwu** [comment]
我翻译了一点，总体量还是比较大。需要帮手 :)

有兴趣的同学可以挑有趣的部分试试。拿不准的名词可以先保留原文。

**Comment by cloudwu** [comment]
翻译其实就是写作，英文能力没太大影响，反正靠 google 都能搞清楚。最终还是靠中文写作能力把句子写流畅。

可以挑有兴趣的独立小段落来。

ps. 今天在打游戏，碰到的每个 event 都忍不住重新翻。

**Comment by linningmii** [comment]
很想下手但是看了一波文本发现一脸懵逼，没玩到DLC完全不能体会他们到底在说什么..还是等周末赶去玩一波游戏再回来看看..

**Comment by cloudwu** [comment]
@linningmii   可以挑觉得有意思的独立模块翻译。

其实 DLC 的内容有两大块，一块是关于几种稀有战略资源的飞地。我翻译了一点点，但是每种资源还有一些文本要翻译。这几种东西之间是相对独立的。

* 旭然集团 （XuraCorp）的旭然凝胶
* 瑞玵交易所（Riggan）的瑞玵香料
* 穆塔钢商人行会 （Muutagan）的穆塔钢水晶

都可以独立出来翻译的。

另一块是关于巨龙的，也包括了不少东西：

* ether drake
* enigmatic fortress
* stellar devourer
* dimensional horror
* asteroid hiver
* infinity machine
* automated dreadnought
* wraith

内容还是相对独立的。

**Comment by cloudwu** [comment]
我把 ether drake 翻译为以太龙兽

https://github.com/cloudwu/stellaris_cn/blob/master/cn/localisation/guardian_l_english.yml#L348-L353

**Comment by yuan1238y** [comment]
The Artisan Troupe
这个东西翻译成什么比较好呢？

**Comment by cloudwu** [comment]
The Artisan Troupe 前面被翻译成 艺术家团体，

如果找到更好的词可以一起替换。

**Comment by soarqin** [comment]
artisan在古英语中可表示艺术家，但是现代英语中只能表示工匠了

**Comment by cloudwu** [comment]
根据上下文理解，这里指的就是艺术家。

**Comment by cloudwu** [comment]
Curators 在上下文中，指的是一个组织，而不是个人。所以不建议翻译成博物馆长。现在我选的译名为：博物馆署。
