### ISSUE TITLE
utopia_ascension_l_english.yml  还有很多待译

### ISSUE THREAD

**Issue by cloudwu** [cloudwu/stellaris_cn#209]
大家加油，准备开干担心重复的，可以先留个言，列一下行号。

**Comment by cloudwu** [comment]
* Whisperers in the Void
* Composer of Strands
* Eater of Worlds
* Instrument of Desire
* End of the Cycle

这五个可以分开分组，多人搞定。

**Comment by Tianchenglipu** [comment]
我比较讨厌天幕的事件 =。=

顺便一提的是贴吧汉化组将shroud翻译成了虚境，是一位领头人物钦点的译法

**Comment by Tianchenglipu** [comment]
大概扫了一眼，哇靠，一点都不想搞，一看就难受啊 =。=
而且当我得知这些都是后后后后后期的低低低低低概率出现的文本的时候我就更不想搞了 =。=

**Comment by Tianchenglipu** [comment]
对这几个天幕中的存在，我先开一下脑洞
Whisperers in the Void 虚空细语体
Composer of Strands 掌命恶体
Eater of Worlds 吞世恶体
Instrument of Desire 极欲恶体
End of the Cycle 圆环终局体

**Comment by wzy9607** [comment]
cycle應該指發展週期、循環。

**Comment by Tianchenglipu** [comment]
那就叫 结世恶体

玩家看不懂啥意思，瞬间爆炸以后就懂了，结束+世界+恶体 =。=

**Comment by wzy9607** [comment]
虛空低語者
命運綫編織者
世界吞噬者
欲朢之器
歷史週期破局者（太長....）

**Comment by inkitter** [comment]
Whisperers in the Void  -  虚空低语
Composer of Strands  -  灾难之源
Eater of Worlds  -  噬世者
Instrument of Desire  -  欲望之器
End of the Cycle  -  轮回之末

**Comment by cloudwu** [comment]
不用一开始全部定下来吧，在翻译每一组的时候，一组的文本都翻译完就可以定一个名词了。

**Comment by Tianchenglipu** [comment]
虚咽恶体
谱命恶体
吞世恶体
极欲恶体
终环恶体

很好，这很恶体！

**Comment by yaxu75** [comment]
https://github.com/cloudwu/stellaris_cn/pull/219里暂时采用的是翻译是

Whisperers in the Void － 虚空低语者
Composer of Strands － 命运谱写者
Eater of Worlds －吞世者
Instrument of Desire － 愿望仪器
End of the Cycle －轮回终结者

如果有后续翻译进行修改不要忘了把term list里的暂译名也一起改了 :)

**Comment by Tianchenglipu** [comment]
我对天幕的事件兴趣真的很小啊 →_→ 一打开就想关了，再加上这几天谜之热，心烦

**Comment by fps40** [comment]
**End of the Cycle** 里的 **Cycle** 应该是指宇宙是循环往复的，从出生到毁灭再到出生。那么 **End** 应该是指宇宙毁灭这个**End**，而不是整个循环被终止了。
"轮回之末"应该是一个比较适合的翻译。
