### ISSUE TITLE
dip_messages_l_english 中一些未完成翻译

### ISSUE THREAD

**Issue by cloudwu** [cloudwu/stellaris_cn#21]
https://github.com/cloudwu/stellaris_cn/blob/master/cn/localisation/dip_messages_l_english.yml#L456-L495

https://github.com/cloudwu/stellaris_cn/blob/master/cn/localisation/dip_messages_l_english.yml#L541

https://github.com/cloudwu/stellaris_cn/blob/master/cn/localisation/dip_messages_l_english.yml#L555-L556

https://github.com/cloudwu/stellaris_cn/blob/master/cn/localisation/dip_messages_l_english.yml#L656-L663

https://github.com/cloudwu/stellaris_cn/blob/master/cn/localisation/dip_messages_l_english.yml#L1138-L1195

@441707521 @airphoenix  你们把它补完怎样？

**Comment by wushukai** [comment]
如果不是很着急，我可以帮忙翻译剩下的
之前没弄过，需要熟悉一下。。

**Comment by cloudwu** [comment]
参与就好，一段也是参与，保证翻译质量优先。有 git 的帮助，不怕工作冲突。

**Comment by soarqin** [comment]
L1138-L1195我正在翻，和参考的句子对比了一下，觉得其实也有不通顺的地方，可能会统一改了

**Comment by soarqin** [comment]
今天翻译dominion相关对话的时候发现全是圣经口吻，似乎dominion是个神学观念，可能自治领这个翻译不太恰当，感觉上应该是个神权统治下的有一定自主权的领地概念，但是翻遍了资料也找不到合适的中文用词，这里提出来征求一下大家的意见想法

**Comment by cloudwu** [comment]
http://www.dictionary.com/browse/dominion

看不出来和神权有关。

**Comment by soarqin** [comment]
我也看不出来，但是那个对白太tm神棍了，我觉得如果所有的dominion相关对话都是这样，很难让人觉得这不是一个神权政治的主从关系

**Comment by cloudwu** [comment]
游戏的 event 和对话的 key 里的词缀会表示这条文本在什么道德观下使用。有时翻译需要参考一下。

**Comment by soarqin** [comment]
嗯，但是这个地方并没有，翻看了之前的文本，确实是这次新加的对话很特殊，风格完全不同
