### ISSUE TITLE
要不要翻译一下随机名

### ISSUE THREAD

**Issue by Tianchenglipu** [cloudwu/stellaris_cn#210]
随着1.5，随机名也支持汉化了，要不要顺便翻译一下呢

**Comment by cloudwu** [comment]
破坏成就吗？

**Comment by Tianchenglipu** [comment]
随机名外置了，所以应该不会破坏成就

**Comment by Tianchenglipu** [comment]
恒星系随机名有不少都是胡诹的，如果实在不想翻译，保留现状就行。
太阳，月亮，这些可以改一改-.-

**Comment by cloudwu** [comment]
我在 mod 里加了  random_names 目录并改了几行，似乎没有影响 checksum 还是 8818 。不过有没有人可以验证一下的确可以解锁成就？

**Comment by cloudwu** [comment]
不行。验证方法：

在 mod 下修改一些想改的文件，比如 random_names 。然后启动多人游戏，勾选 相同的版本 ，如果能找的到服务器就说明对版本验证无影响。

目前打上本汉化后，是没有影响的；但是修改了随机名字就匹配不到了，说明有影响。

**Comment by soarqin** [comment]
多人游戏可能是为了随机名字一致性不让你匹配，不代表成就拿不到，成就还是要单独测试一下

**Comment by cloudwu** [comment]
从实现的角度，应该只有一套研究完整性的方案。我好拿的成就已经拿完了，谁方便实验可以试一下。

**Comment by cloudwu** [comment]
至少会导致打上 mod 上无法正常(默认选择同版本匹配）联机 :)

**Comment by inkitter** [comment]
现在的bug就在于不管开了什么mod，checksum都是8818。。。
游戏文件夹里的 checksum_manifest.txt 里面写了，localisation_synced文件夹是计算checksum的。

**Comment by Tianchenglipu** [comment]
……那我们还是不要汉化了吧。可恶的瑞典蠢驴。

**Comment by Tianchenglipu** [comment]
我目前一个成就都没拿，因为我离开自己的mod就没法玩 :)
