### ISSUE TITLE
events_l_english

### ISSUE THREAD

**Issue by yiyuandian** [cloudwu/stellaris_cn#211]
用的notepad++看的，不确定行数会不会对
	834:殖民者发现几乎所有的植系都会想不同方位迁移。
		想→向
	847、849:现在树以成灰，开采不是问题
		以→已
	861:对地震进行调查时，科学家发现了庞杂的底下洞穴网络。
		底下→地下
	1132:这些手无缚鸡之力的鸟人之类的，靠着长长的腿走路。
		语义奇怪
	1135:我们在[From.GetPlanetMoon]地表发现了古代安装遗迹。
		installation 的翻译
		名词
		安装installation
		设备equipment, device, apparatus, facilities, installation, implement
		设施facility, installation
		装置物fixture, installation
	1151:这一个文明是在第一联盟崩溃后受到一群星际奴隶主的袭击而毁灭的
		这一个→这个（？）
	1201:科学家设法推测除了伊瑞斯的星系坐标
		除了→出了
	1203:系统的轨道轰炸了
		系统的→系统地(？)

**Comment by cloudwu** [comment]
请直接提 pr, 这样无法合并。

**Comment by Tianchenglipu** [comment]
你直接改文件就行了。进入该文件，点一下右上角那个铅笔，改好了网页版会引导你创建一个pull request。
