### ISSUE TITLE
天幕里的五个灵体，这样翻译好不好呢？

### ISSUE THREAD

**Issue by Tianchenglipu** [cloudwu/stellaris_cn#225]
```
Whisperers in the Void → 虚咽灵尊
Composer of Strands → 谱命灵尊
Eater of Worlds → 吞世灵尊
Instrument of Desire → 极欲灵尊
End of the Cycle → 终寰灵尊
```

我支持保持字数一致，而且要在名字里有共通部分，好使这些名字具有一定程度的一致性。OOXX的格式是比较好的，OO的部分表示个性，XX的部分表示共性。

表示共性的部分，一开始我想到的顺口的，就是从万智牌里抄来的“恶体”。但是，这几个东西并不一定总是恶的，天幕里的灵体有的时候还会给点好处的，并不总是搞破坏，所以不太适合直接在这里讲它是善是恶。后来经过朋友提示，其实可以用“灵尊”，因为它们是上古超强灵能存在，在此基础之上没有更多情报，因此灵尊十分符合。

**Comment by Tianchenglipu** [comment]
贴吧汉化组的翻译是：

```
虚空之低语
生命之织缕
世界之喰煞
渴求之器具
轮回之终末
```

呃，是不是日系轻小说看多了。

值得一提的是，“喰”这个字就取自某个日系轻小说的标题，要不然你以为怎么会想到这个字。

**Comment by Tianchenglipu** [comment]
之前的“国是”，其实是一个常见的正式场合的词语，中国大陆的新闻媒体经常使用。说实话，我从不看新闻，所以当我知道这件事以后，我瞬间就明白了他们为什么会想到这个词。要不然还能怎样，总不见得是翻阅古文看到的吧。

**Comment by cloudwu** [comment]
国事和国是的区别是高考语文题啊

**Comment by Tianchenglipu** [comment]
那我高考的时候怎么没见到 = =

**Comment by Tianchenglipu** [comment]
这几天发生了大异变，我的生活中突然出现了一个常用词，而这个常用词在以前我闻所未闻，那就是——国是。

**Comment by cloudwu** [comment]
居然高三语文老师不讲？很容易就丢了三分，然后没上一本线的。

**Comment by Tianchenglipu** [comment]
您多大 -。- 要我猜的话，我认为31岁程度

**Comment by Tianchenglipu** [comment]
好老师是很难求的，尤其是语文的好老师。

**Comment by cloudwu** [comment]
就快 40 了 -_-

**Comment by cloudwu** [comment]
要我说, world eater 明明是饕餮。

**Comment by Tianchenglipu** [comment]
饕餮灵尊，不好吧。

虽然饕餮本来是名词，后来逐渐用多了可以当作动词使用，但是饕餮灵尊还是不好啊。

如果弃掉灵尊，单独用饕餮，其实也是不好的，因为饕餮不是个独行侠，饕餮有多达8位同伴。

**Comment by Tianchenglipu** [comment]
`End of the Cycle → 终寰灵尊`
这个，本来的计划是终环灵尊，发现其实可以将环替换为同音字的寰，而寰可以表示寰宇。虽然寰不一定是个圆环，但这样翻译表义上是很准确了。

PS. 我很喜欢终寰恶体，但翻译不能夹杂私货。

**Comment by Tianchenglipu** [comment]
既然您讲了年龄，我也讲一下我的。
现年20岁 -。-

**Comment by cloudwu** [comment]
我觉得都可以，不过我希望在那部分完成后，再替换。

**Comment by Tianchenglipu** [comment]
都可以是指
环vs寰
还是
灵尊vs恶体

**Comment by cloudwu** [comment]
看起来 灵尊 好一点。不过需要把其他文本翻译好研究一下。

end of circle 放佛教里就是涅槃的意思吧。

**Comment by Tianchenglipu** [comment]
翻译了一部分了。没有我想象的那样无聊，但是我现在不在耐下心来好好搞的气氛。让我先玩会游戏吧 -。-

**Comment by Tianchenglipu** [comment]
翻译好了！快 merge 呀！ :)

**Comment by Tianchenglipu** [comment]
看起来灵尊多数时候还是干坏事的，如同地狱里的五个恶魔。叫它们恶体也是可以的。 -。-

**Comment by cloudwu** [comment]
如果最终觉得恶体好就换过来。
