### ISSUE TITLE
Station，Curator，Enclave这三个词

### ISSUE THREAD

**Issue by Tianchenglipu** [cloudwu/stellaris_cn#240]
目前的文本把Station都写成了“基地”，这有点很那啥。还是叫“空间站”吧……目前还没有放在pr里。

目前的文本Curator前后不统一，我刚顺手在我的pr里按照terms里的词语统一了一下。我的意见是“博库管”。目前还没有放在pr里。

Enclave翻译成城邦应该不会有人有意见。因为飞地的意思是，某国有一小块领土完全被别国的领土包围。然而空间站就是他们的全部，此外Enclave在游戏里也是不会产生国界的。飞地→城邦的替换已经放在了我的pr里。

**Comment by cloudwu** [comment]
station 的讨论 https://github.com/cloudwu/stellaris_cn/issues/47
curator 的讨论 https://github.com/cloudwu/stellaris_cn/issues/89
enclave 翻译成飞地也很准确啊。https://en.wikipedia.org/wiki/Enclave_and_exclave  不产生国界才是正常的。
