### ISSUE TITLE
百度贴那个汉化好渣

### ISSUE THREAD

**Issue by epfte** [cloudwu/stellaris_cn#245]
玩起来真心感觉奇怪

**Comment by epfte** [comment]
速子光矛给翻译成快子 笑死了

**Comment by epfte** [comment]
cry！2333

**Comment by epfte** [comment]
算了不改了这里有哈哈

**Comment by epfte** [comment]
我拿去用了谢谢啦

**Comment by epfte** [comment]
还有关于科技第248行翻译成 掠夺者导弹 或 劫匪导弹都OK。 #嘲笑贴吧汉化组

**Comment by epfte** [comment]
这里文本有了但是还不可以直接拿去用，加工一下 要不界面全是？？？？？乱码

**Comment by wzy9607** [comment]
#6

**Comment by wzy9607** [comment]
#6 需要單獨下載字體Mod

**Comment by fps40** [comment]
我认为有一些专有名词反而是贴吧的更符合我们的习惯。
当然，汉语语文水平比贴吧好太多了。贴吧的像是初中生的语文水平。
@epfte 快子这个翻译没有什么问题，快子和速子是一样的东西。快子听起来像“筷子”，后面接“长矛”时，还是“速子”更好听些而已。

**Comment by Tianchenglipu** [comment]
快子是没问题，但是速子比快子好听。

cloudwu的语文好我是认同的，看到倍燃石我就明白了。

贴吧汉化组最主要的问题是在各种意想不到的地方胡乱加私货，根本不是严肃搞翻译的态度。除此以外就是分工方式不科学的缘故，经常出现前后不一，以及机翻与手翻混杂、质量参差不齐。

**Comment by Tianchenglipu** [comment]
客观来说， Stellaris 贴吧汉化组的第一个主要问题是在各种意想不到的地方胡乱加私货，根本不是严肃搞翻译的态度。他们的翻译文本随处可见包括 +1s 在内的各类网络俗语，非常容易让观看者出戏。而如果要一个个揪出来改掉，你会发现效率最高的方法是自己手翻，不用他的。一般某某贴吧汉化组的成果，如果里面的网络俗语不超过 3 处，那就非常值得庆幸。

第二个主要问题就是分工方式不科学的缘故，经常出现关键用语前后不一，以及机翻与手翻混杂的现象。关键用语前后不一，是因为译者没有做好协调工作。至于机翻混手翻，我想大部分的贴吧汉化组最开始并不想这样子，只是这种交差事的工作方法容易激起人本能的交差心理。为什么我们的译者会偷懒呢？首先是译者太多，你如何确保每名译者都是一丝不苟的呢？然后是催稿，再加上没有任何针对偷懒的审查机制和惩罚，这会导致被催稿者更加乐意选择偷懒。这就是所谓交差事工作方法。

第三个主要问题就是语文水平。为什么放在最后讲，因为语文水平不能量化，为了说明语文水平是高是低，必须拿翻译的具体结果来对比，而我实在是懒得这样做，而且如果一个固执己见的人认为某种翻译比较优秀，那么没有任何办法让他承认另一种翻译比较优秀。所以看过文本的人明白就行。

有趣的是，各类贴吧汉化组基本上都会出现这些问题，这还真不是 Stellaris 贴吧汉化组的特色。

PS：加私货就是指在非私人的决策上添加私人因素。例如某某市长被狗咬了以后下令全市禁止养狗，就属于私货行为。

有趣的是，如果有关注本项目的最近改动情况的话，就会发现其实本项目的变更并没有太频繁，就连看似很活跃的我也不是每天都在做事的，综合起来在做事的时间可能没有达到 24 小时。然而即便如此，我们的效率还是更高，完成任务轻松愉快， cloud wu 在 2017 年 4 月 16 日就已在创意工坊宣布基本翻译完了。相比之下， Stellaris 贴吧汉化组在 2017 年 4 月 17 日宣布汉化完毕，虽然两者的日期比较接近，但贴吧汉化组曾宣称翻译情况告急、以前的成果多数作废、最恶的场合可能会在五月以后完成。由此可见这是什么样的管理能力和效率差。

**Comment by cloudwu** [comment]
专有名词有建议的，可以先在 issue 搜索一下看看之前有没有讨论过。没讨论过的可以开新帖。

由于有大量文本是之前从官中继承过来的，并没有校对，玩的时候有发现不统一或想校对的，可以直接提 pr ，这样效率比较高。

ps. 这几天我在玩 2b 小姐姐，所以没碰群星，待我三周目完结再继续。

**Comment by Tianchenglipu** [comment]
你这个死宅 -_-
而且 2b 小姐姐都要保持空格是何等的强迫症。
