### ISSUE TITLE
最近上传的一些存档地图螺旋2臂Blorg commonality

### ISSUE THREAD

**Issue by epfte** [cloudwu/stellaris_cn#246]
https://github.com/epfte/Stellaris-Galaxy-Edition-v1.5.1-Incl-ALL-DLCs/tree/master/save%20game/blorgcommonality

**Comment by epfte** [comment]
地图大小中型

**Comment by Tianchenglipu** [comment]
这是什么？

**Comment by epfte** [comment]
这是游戏的存档

**Comment by epfte** [comment]
没人要吗？😓还有简体中文字体，可以复制到mod目录直接使用。

**Comment by epfte** [comment]
神秘要塞你怎么打。这玩意火力好强，貌似要大航队过去才能拆。😱

**Comment by epfte** [comment]
💀看起来比群星吞噬者 以太龙 还强大

**Comment by epfte** [comment]
现在的战舰武器配置速子光矛x1 后全L位 相位解离器x3 等离子火炮x1 我就不信拆不过这玩意👽

**Comment by epfte** [comment]
600军舰容量 69K战斗力 正合适，打完不要白送陆军，选让科研船过去，选二项第一项直接失败。重新摆放金属环 之后选择探索星系  选建造过程的中间段 。不要选第一，神秘要塞会恢复起来你附近的科研船一个也别想跑。完成奖励神秘护盾 能源黑科技

**Comment by epfte** [comment]
我旁边有个圣地守卫者，殖民丢给AI 之后.....2333了

**Comment by Tianchenglipu** [comment]
这里是 cloud wu 的翻译项目。 issue 是用来对项目提意见和讨论问题的地方。你这些更适合放在百度贴吧。

**Comment by Tianchenglipu** [comment]
@cloudwu  要不要开一个聊天 QQ 群？还是说今后允许在 issue 里面聊天？

**Comment by cloudwu** [comment]
issue 尽量避免闲聊吧，我这种用 email 订阅的都被刷了。

**Comment by Tianchenglipu** [comment]
您用不用 QQ -_-

**Comment by cloudwu** [comment]
不用，email 包打一切，还用那些干什么。

**Comment by Tianchenglipu** [comment]
既不想用 QQ 又不想允许 issue 闲聊，那就没地方闲聊了 -_-

**Comment by cloudwu** [comment]
你们建 qq 群好了，我不参加。

**Comment by epfte** [comment]
你们闲聊可以来我的issues下聊。准备OK
https://github.com/epfte/epfte/issues/1

**Comment by epfte** [comment]
或者来我的 https://Twitter.com/epfte

**Comment by epfte** [comment]
![2017_05_07_3](https://cloud.githubusercontent.com/assets/27140154/25931892/b719158c-3641-11e7-81f6-47bb84cc306c.png)
![2017_05_07_4](https://cloud.githubusercontent.com/assets/27140154/25931893/b75a9606-3641-11e7-96ef-a0111e5d2a36.png)

**Comment by epfte** [comment]
这是什么问题 建造戴森球完毕 弹出utopia.41000.name

**Comment by epfte** [comment]
这是什么
