### ISSUE TITLE
话说英文文本里面有一个 air_l_english.yml

### ISSUE THREAD

**Issue by Tianchenglipu** [cloudwu/stellaris_cn#247]
这个文本里有什么航空母舰啊，王牌飞行员啊，感觉根本就是从钢铁雄心里弄过来的。而且有趣的是只有英文文本有，其他语言的文本全都没有这个文本。

这是瑞典蠢驴的新的失误吗？

**Comment by inkitter** [comment]
是你操作失误造成的意外文件吧。。

**Comment by Tianchenglipu** [comment]
哪有凭空多出一个文件的道理。还是汉化的，而且和 cloud wu 的其他文本一样，英文和中文之间有空格。

**Comment by inkitter** [comment]
我写的那个 Translator 压缩包里带了一个样本文件，应该恰好是 HOI4 的 air_l_english.yml，可能是你玩的时候不小心复制进去了吧。

**Comment by Tianchenglipu** [comment]
然而我看了一下原版英文文本发现确实有一个 air_l_english.yml 。难道这是一个巧合？
