### ISSUE TITLE
l_english.yml中一些翻译问题

### ISSUE THREAD

**Issue by fps40** [cloudwu/stellaris_cn#248]
**l_english.yml** - 3047行
>  leader_trait_curator:0  "馆长"

**Curator** 作为一个外星种族的名称，直接翻译为馆长实在不妥吧。有个现成的词，“策展人”，我觉得就很好。
策展人全称”展览策划人“，是指在艺术展览活动中担任构思、组织、管理的专业人员。不管你是博物馆馆长还是别的什么馆长，其含义已经包含其中了。
而且用作外星人名称，过于直白会感觉很搞笑，还是”策展人“这种更高级的词汇比较适合。

**Comment by Tianchenglipu** [comment]
Curator 不是物种的名字。
既然知道策展人的意思是展览策划人，那就更不应该用在这里了，因为想也知道他们不是干这个的。
