### ISSUE TITLE
太空游戏，你们翻译成基地..我呢呵呵

### ISSUE THREAD

**Issue by epfte** [cloudwu/stellaris_cn#262]
太空游戏，你们翻译成基地。
我想我会翻译成 轨道站 空间站会更合适。

**Comment by epfte** [comment]
TECH_UNLOCK_SPACEPORT_CONSTRUCTION_TITLE:0 "§H解锁空间站：§! 太空港"
 TECH_UNLOCK_FORTRESS_TITLE:0 "§H解锁空间站：§! 要塞"

**Comment by epfte** [comment]
你觉得你们翻译的合适吗  
TECH_UNLOCK_WORMHOLE_1_TITLE:0 "§H解锁基地：§! 虫洞站"

**Comment by cloudwu** [comment]
有话好好说。

**Comment by epfte** [comment]
以上是的想法。一些太空建筑 用基地一词觉得这感觉有点...无语....

**Comment by Tianchenglipu** [comment]
查看已关闭的 issue 可以看到有关讨论
