### ISSUE TITLE
派系名 "三月勇气"

### ISSUE THREAD

**Issue by pigheadx** [cloudwu/stellaris_cn#263]
March 不应该是三月,应该是进军的意思,这个派系是军国主义的帝国主义派名字.建议修改.

**Comment by cloudwu** [comment]
麻烦找一下条目，我找不到。

**Comment by cloudwu** [comment]
我没见过三月勇气，你是不是装了别的什么 mod 。

**Comment by Tianchenglipu** [comment]
派系名汉化MOD吧

**Comment by pigheadx** [comment]
Sorry, 确认了一下是 Chinese random name 里面的内容, 不是这里的.
