### ISSUE TITLE
1.6出了官方中文，不过貌似默认没开启，添加代码在启动器里就可以选了。

### ISSUE THREAD

**Issue by inkitter** [cloudwu/stellaris_cn#264]
在languages.yml添加
```
l_simp_chinese:
 l_simp_chinese:0 "Chinese"
```
星系和飞船自带汉化挺好的。
字体丑。

**Comment by cloudwu** [comment]
https://github.com/cloudwu/stellaris_cn/commit/9b246482df3c86df2615e37be0482cf640f744e4

我们还是继续维护吧，可以挑出来合并官中。

**Comment by cloudwu** [comment]
https://github.com/cloudwu/stellaris_cn/commit/9b246482df3c86df2615e37be0482cf640f744e4

我们还是继续维护吧，可以挑出来合并官中。

**Comment by Tianchenglipu** [comment]
官方中文缺字 -_- 我好奇想看一下官方中文怎么翻译 devouring swarm ，结果毛也没搜到，我还以为是我拼错了

**Comment by cloudwu** [comment]
1.6 更新不多，偷懒的话可以直接把关中对应条目搬过来。

**Comment by LazyZhu** [comment]
@cloudwu 
得另外做一个mod，就是把文件
localisation\english\*_l_english.yml
都改成
localisation\simp_chinese\*_l_simp_chinese.yml
并把游戏设置成中文
这样的好处是以后可以使用自带的随机中文名(https://tieba.baidu.com/p/5108879539)而不影响铁人成就。

**Comment by LazyZhu** [comment]
测试了1个小时，没啥问题：
![2017-05-09_164554](https://cloud.githubusercontent.com/assets/2244967/25872018/4af49cf2-34d7-11e7-95ee-6d60af8803f5.png)
![2017_05_09_1](https://cloud.githubusercontent.com/assets/2244967/25872031/5498037a-34d7-11e7-97c9-34a687f5d5fa.png)

**Comment by LazyZhu** [comment]
仅供测试:
Stellaris\mod\[cn2.zip](https://github.com/cloudwu/stellaris_cn/files/987975/cn2.zip)

+

Stellaris\mod\cn2.mod
name="Cloud Wu's Chinese Localisation V2"
path="mod/cn2.zip"
tags={
	"Translation"
}
supported_version="1.6.*"

**Comment by Lugic1993** [comment]
请问，需要我尽一些绵薄之力吗？可以做些什么呢？

**Comment by Tianchenglipu** [comment]
之前更新又把中文给去掉了。

**Comment by Lugic1993** [comment]
官方的中文显然和这里的中文比差远了
其次，贴吧中文版各种花式膜蛤，对我而言是极好的

**Comment by inkitter** [comment]
官中又被退回去了，所以关掉issue了。

**Comment by cloudwu** [comment]
有没有人留了偷跑的官中文本的？

**Comment by Tianchenglipu** [comment]
对不起，我没留。不过 @inkitter 应该有留吧？？
