### ISSUE TITLE
1.61 需要翻译的文件

### ISSUE THREAD

**Issue by inkitter** [cloudwu/stellaris_cn#269]
量都不大，文件如下：
dip_messages 完成
events_2 完成
events_3 完成
events 
l_english 
messages 完成
modifiers_2 完成
modifiers 
pop_factions
technology 完成
traditions 完成
triggers 完成
utopia
utopia_megastructures 第12，14行

**Comment by cloudwu** [comment]
utopia 后面还有很多没有翻译，有没有留上次官中的文本？可以先替换一下。

**Comment by inkitter** [comment]
上次的官中并没有1.6新加的文本。。。所以又被撤掉了
https://github.com/inkitter/pdx-ymltranslator/tree/master/release/old/st-1.60-cn
我是有个备份的
