### ISSUE TITLE
提交一个翻译的别字

### ISSUE THREAD

**Issue by Dannyrole** [cloudwu/stellaris_cn#271]
新游戏的种族编辑界面，军国主义的完全轨道轰炸政策，翻译是权利轨道政策，应该是错别字。可以麻烦修改一下吗。谢谢

**Comment by epfte** [comment]
自己打开找用N++
![s170511130743](https://cloud.githubusercontent.com/assets/27140154/25933634/e0c56ac6-364a-11e7-9153-9b1a98fc96ca.png)
