### ISSUE TITLE
……搜出了另一个汉化组的git

### ISSUE THREAD

**Issue by AmagiReturned** [cloudwu/stellaris_cn#294]
https://github.com/GalAster/StellarisCN

贡献者很少，没有任何讨论。

**Comment by cloudwu** [comment]
好像是把 issue 关了。

**Comment by AmagiReturned** [comment]
而且并没有怎么宣 -_- 似乎并不希望开放修改

**Comment by AmagiReturned** [comment]
虽然贡献者有超过十位，但是贡献者只有四位，可见这个git就算是对于组内也是内绪。
