### ISSUE TITLE
1.8 新文本翻译（还有一些未完成，列表在此）

### ISSUE THREAD

**Issue by cloudwu** [cloudwu/stellaris_cn#326]
昨天晚上我已经更新了 1.8 版的所有文本。大家可以开干了。可以通过查询 merge 1.8 这个 commit 查看变更：https://github.com/cloudwu/stellaris_cn/commit/e2a231967b2557109d88c4563262146a0a06404e 
或者使用 blame 功能。

下面是点名时间 :)

@AmagiReturned @wzy9607 @inkitter @soarqin @yaxu75 @BurningRainbow @mrgump @mo805241560 @zsc19921016 @shruggedwm

**Comment by FrailLeon** [comment]
路过兹磁一下 👍

**Comment by ClockTower412** [comment]
愿意参与翻译工作
stephenstark@foxmail.com
qq2921033949
曾参与多个游戏汉化小组 对游戏翻译有一定经验

**Comment by cloudwu** [comment]
不用报名确认，直接 fork 翻译提交 pr 即可。尽量不要提交太大的 patch ，已防止冲突。我会每天统筹安排合并。

ps.  注意统一术语 https://github.com/cloudwu/stellaris_cn/blob/master/terms_list.txt ，有 1.8 引入的新术语，可以在 issue 里先讨论，翻译可暂时保留英文。

**Comment by cloudwu** [comment]
如果翻译的句子里有保留英文待确定，在行末加一个 #TODO 单词 方便日后检索。

**Comment by wzy9607** [comment]
未完成翻譯的文件統計（未計入TODO）：
[ ] l_english.yml trait和start screen
[ ] events_l_english.yml
[ ] events_2_l_english.yml
[ ] events_3_l_english.yml
[ ] events_4_l_english.yml
[ ] synthetic_dawn_events_l_english.yml
[ ] dip_messages_l_english.yml
[ ] tutorial_l_english.yml

**Comment by cloudwu** [comment]
所剩不多，大家是不是分工合力突击一下？

**Comment by cloudwu** [comment]
同学们，现在只剩 dip messages 文件里的一点对话了。大家加油搭把手吧，一人一天一句很快就全部搞定了。缺的部分我列在上面的帖子里了。

**Comment by sunzhuoshi** [comment]
提交了一个PR， 翻译了一部分dip_messages_l_english.yml内容。
不过已有翻译似乎没有完全统一术语？我改翻译的时候发现跟之前的有不一致的地方：比如臣属国的翻译，之前有翻译成附庸国的；协约国有翻译成签约国的。。。

**Comment by cloudwu** [comment]
谢谢。这个翻改了多次，不同人经手，所以只能看到有问题的时候再改了。

**Comment by cloudwu** [comment]
终于搞完了，结帖了。
