### ISSUE TITLE
organic的翻譯

### ISSUE THREAD

**Issue by wzy9607** [cloudwu/stellaris_cn#336]
organic creator我暫時翻譯成了有機創造者。

**Comment by cloudwu** [comment]
organic 在这次的文本中出现了 500+ 次，应该是一个核心词。

我的个人意见是，突出科幻色彩，并强调是一个游戏专有词的话，简单些 **有机** 有可能造成上下文歧义。

是不是翻译成 **有机生物体** 会显得慎重一些？可能需要多翻译一些包含这个词的条目后，才能做判断。

**Comment by syj2010syj** [comment]
organic看起来是机械文明对有机文明的称呼，只有机械文明使用，有机文明不会用来自称，可能是带有贬义的词语

**Comment by fqqdc** [comment]
比如我们称呼机械体为机器人、机械生命。
按照常见故事剧情中机器人那种生硬的思维，机器人称呼其他生命体为：有机体。书面一点：有机生物。
我感觉这样顺口一下。
