### ISSUE TITLE
1.8 新增术语的讨论帖

### ISSUE THREAD

**Issue by cloudwu** [cloudwu/stellaris_cn#339]
由于这次 DLC 新增加了很多术语，在没有通读整个文本，深入玩游戏前，选择合适的中文词会比较困难。

所以建议暂时这样处理：

* 如果拿不太准的词，可以保留原文，并在对应条目最后加上 #TODO 英文原文词 。
* 如果自己选了一个翻译词，但可以有异议，以后可能会修改，可以在对应条目后加上 #TODO 英文 暂定中文翻译
* 如果自己选了一个比较满意的词，可以直接使用，但在 term_list 文件中注明。然后在本贴下讨论。

**Comment by syj2010syj** [comment]
nanite 纳米机器人

**Comment by syj2010syj** [comment]
Machines 智械
需要和Robot（机器人）区分

**Comment by syj2010syj** [comment]
warform
之前数量比较少，被翻译为了“战体”
这次数量增加了很多，感觉“战体”不是很合适

**Comment by syj2010syj** [comment]
positronic 阳电子
代表尖端科技的一个词
吃我阳电子炮！

**Comment by syj2010syj** [comment]
Machine Intelligence
一开始以为是类似蜂群女王的存在，后来发现有一群，但不是每个智械都有，并且有Machine Intelligence之间有主次之分（primary Machine Intelligence）

**Comment by syj2010syj** [comment]
Colony Fabrication Drones
好像是机械文明的殖民船，找不到合适的词

**Comment by syj2010syj** [comment]
synthetic worker 合成人建造者？
其实我不是很喜欢XX者的翻译，不过用工人看起来更不合适

**Comment by syj2010syj** [comment]
drone population
无人机的人口，意思传达给我了，但是找不到词来表述

**Comment by cloudwu** [comment]
Machine 智械 属于一个自造词，感觉有点点别扭。机械体 怎样？我还没有深入看文本，不清楚各种上下文处和词组里怎样。

**Comment by cloudwu** [comment]
positronic 不常规是正电子么？

**Comment by cloudwu** [comment]
warform 在之前的版本中特指 cybrex 的战舰，这次应该顺着用于 AI 势力的战舰了。

**Comment by wzy9607** [comment]
Bio-Trophy
trophy是战利品，-trophy是营养，具体含义待观察。

**Comment by fqqdc** [comment]
有一段事件剧情中提到了 Machine World，用来形容被Machine占领的星球的类型

**Comment by cloudwu** [comment]
**机器** 的问题是不像一个专有名词，而且在游戏中 Machine 是和 Organic 相对应，应该找一对词会好一些。

所以我暂时定为 **机械体** 和 Organic 为 **有机体** 再看后面根据不同的上下文怎样调整。

Machine Intelligence 我改成了  **机械智慧体** 在游戏中似乎指的是 Machine 的政府形式。这个 commit 是我的修订：

https://github.com/cloudwu/stellaris_cn/commit/6f225a57f9b3ae6c754bedd868e09872adedb22d

**Comment by cloudwu** [comment]
Bio-Trophy 我猜想指的是 黑客帝国 里那种由机器圈养的人类（当电池用）这种。

**Comment by cloudwu** [comment]
我刚才开了一局，发现 Bio-Trophy 可以翻译成 生化电池 非常贴切。

**Comment by zaxAngus** [comment]
the contingency 这个词是怎么翻译？

**Comment by syj2010syj** [comment]
drones
这个名词目前被标注为了 **无人机**
但目前文本中，蜂群也会用这个词
我目前将其译为 **蜂群**

**Comment by syj2010syj** [comment]
查了一下之前的翻译，蜂群的 **drones** 应该翻译成 **工蜂**

**Comment by syj2010syj** [comment]
biomass
看起来是指用来吃（蜂群）或用来发电（机械体）的生物集群

**Comment by AmagiReturned** [comment]
阳电子是日本和TW对正电子的叫法。叫阳电子也没什么不对。

**Comment by AmagiReturned** [comment]
我不懂瑞典人为什么要把 Robot 和 Machine 分开，显得怪怪的。
我的建议是：「机器人」，「机械族」。
机器人表示是有机文明的从属品，机械族表示自成文明。

不过其实，我更希望这两者不作区分。

**Comment by cloudwu** [comment]
Machine 是游戏专用名词，不应完全按常规字面含义去理解。
Robot 则是常规词，符合日常字典含义。

**Comment by wzy9607** [comment]
Contingency
https://forum.paradoxplaza.com/forum/index.php?threads/stellaris-dev-diary-72-crises-the-contingency.1026439/
似乎被译成紧急情况了

**Comment by zaxAngus** [comment]
the contingency貌似是被翻译成紧急协议了，我感觉是一个组织的名字，这样叫很糊涂。我感觉专有名词会不会先都保留一下英语好一点

**Comment by zaxAngus** [comment]
bio-trophy，提到这个的种族背景好像是机器人是一种服务狂，替代了造物主所有的工作，然后有机生命体就可以只享受生活了，现在想去解救全宇宙的有机生物，让他们都不工作享受生活。bio-trophy貌似就是指这种的citizenship，生化展品好像感觉有点不太贴切贬义太多了？相比战利品我感觉更多的是一种纪念生物形式的感觉，感觉翻译成生物纪念？

**Comment by fqqdc** [comment]
the contingency，是一个入侵势力的名称。是银河各个国家对他们的称呼。

但是他们本身是他们的造物主留下的一种应对某种事件的机制。

而且这个机制的完整名称就叫做the contingency protocols，这是在原文中提到的。

**Comment by zaxAngus** [comment]
我感觉这个名字在这里翻译成计划，比如应急计划，会不会稍微好理解一点

**Comment by fqqdc** [comment]
字面本身应该叫应急机制之类的，但是它整体是一个跨越相当长时间的危机事件的名称，有完整的从小到大发展的剧情要素。

不像一个突发的让人措手不及的灾难结果的描述，所以我才选了一个跟字面意思不怎么贴合和词语。

**Comment by cloudwu** [comment]
bio-trophy 就是有贬义的意思，他们已经沦为从属种族，而且失去了大多数权利了。
