### ISSUE TITLE
兩對翻譯混淆

### ISSUE THREAD

**Issue by wzy9607** [cloudwu/stellaris_cn#344]
1. Cybrex （先驅文明）与Cybernetic/Cyborg （升飛）都翻譯成了賽博；
2. 如果Machine翻譯成「機器」有幾處會与Robot相混。

**Comment by cloudwu** [comment]
Cybrex 建议恢复成我之前的翻译：赛博霸王。 rex 是霸王龙的意思。

**Comment by cloudwu** [comment]
Machine 能否考虑用 **机械体** ?

**Comment by wzy9607** [comment]
我倾向于把cybernetic（模控論）、Cyborg（半机械人？）意译。

**Comment by AmagiReturned** [comment]
Cybrex 我想的翻译是「赛博瑞」。
