### ISSUE TITLE
interface 文件夹应该删除

### ISSUE THREAD

**Issue by inkitter** [cloudwu/stellaris_cn#387]
interface中fonts.gfx等文件控制字体，本mod只有汉化作用，并没有字库，使用这些文件会影响到其他字体mod的兼容性，导致其他mod字体失效或产生其他问题。个人认为不应保留该文件夹。

**Comment by cloudwu** [comment]
我测试过，不影响其它字体 mod 。

**Comment by cloudwu** [comment]
这个是为了减少使用 mod 的人的提问。不看说明的人太多。

它目前只是复制了原版文件，把指向中文的字体定义转向英文（因为原版没有把中文选择放出来）。相信过不了多久官中就出来了，那个时候就可以删除。

**Comment by cloudwu** [comment]
看起来 P 社的 mod 优先级规则是按 mod 名称字母排序的。排前面的先加载，后面的同名文件就忽略了。

**Comment by inkitter** [comment]
就是因为做过几个mod，了解群星的mod排序支持不太友好，所以会提出这个issue。。。
最近比较忙，早晨pull一看发现了这个问题。

PS: 我新做的1.8版字体mod是ttf格式（1.6更新之后开始支持ttf格式的字体），很多人反应会闪退，目前估计就是字库索引文件相互覆盖混乱导致的。

**Comment by cloudwu** [comment]
https://forum.paradoxplaza.com/forum/index.php?threads/please-explain-mod-loading.935895/  这里的讨论是说字母次序。

直接 mod 掉官方的中文 ttf 保持一样的路径是不是兼容性会好一些？

**Comment by inkitter** [comment]
主要是考虑体积。如果像官方用一堆字体文件来覆盖，还不如用原来的图片方式了。。。而且目前字体文件还有垂直位置浮动的问题，不是太好的方案。还是用回tga吧。
