### ISSUE TITLE
是否应该考虑把古风的特质名换掉？

### ISSUE THREAD

**Issue by AmagiReturned** [cloudwu/stellaris_cn#419]
很多人都对这些古风特质名非常不满。我认为应该将它们全部换成更加朴素直白的表达法。

**Comment by cloudwu** [comment]
很多人是指谁？
现在的翻译并没有表达不清的问题。

**Comment by AmagiReturned** [comment]
在贴吧看到了许多类似反馈。甚至有人 fork 过来专门改这些特质名。
至于表达清楚不清楚不是首要问题。首要问题是受众听起来感觉怎样。
如果你很喜欢这些古风的特质名，愿意将之保留，那就作罢。

**Comment by cloudwu** [comment]
贴吧有原有的翻译，总有先入为主的看法。
如果有反馈应该先把反馈链接贴过来。

感觉和个人影响太大，总不能有人反馈就改一次。

**Comment by cloudwu** [comment]
fork 就是用来解决这种喜好问题的。

**Comment by AmagiReturned** [comment]
其实我第一次看到这些特质名也想吐槽，不过好在我可以自己修改，所以没有跟你提。真正想改是因为看到了别人吐槽，坚信这是一个急需修改的地方。

https://tieba.baidu.com/p/5345560906 34L & 38L

先入为主这一点我非常同意。目前贴吧大部分用户对你的劳动的态度是_“出得比贴吧汉化组快，用作临时代替，总好过英文”_，但是我认为不能因为这样就把所有问题都归结为先入为主。此外，会对你的劳动抱有这种态度的人大概率不会对你提建议。会对你提建议的一定是你的忠实用户。

**Comment by cloudwu** [comment]
我赞同修改那些不能顾名思义的地方，但反对因为个人喜好就修改已有翻译的很明确的地方。翻译是一个整体，这里希望保持一致的风格。

特质最早的翻译有很多不准确的词，并不能正确表达英文的意思。换一批翻译并不是仅仅想用另一种风格表达。

**Comment by cloudwu** [comment]
https://github.com/cloudwu/stellaris_cn/commit/7e351e3cb4151544c90fbeaf793524ad299d7100   葆力之士 -> 勤奋努力

**Comment by AmagiReturned** [comment]
我可不会帮你把机械特质也处理成四字的古风的那种 -_-
