### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by hkfires** [cloudwu/stellaris_cn#438]
1、文字剃头现象，如图，在输出总数的地方
![20171011225755_1](https://user-images.githubusercontent.com/10558748/31479754-e5929c16-af4b-11e7-85f1-c4d7b10e3251.jpg)
2、科研项文字变成代码
![20171011225424_1](https://user-images.githubusercontent.com/10558748/31479767-ff9f8f4c-af4b-11e7-8a73-deb9b9d25f61.jpg)

**Comment by cloudwu** [comment]
第二个问题是 1.8.2 新增词条，今天更新后应该没问题了。

第一个问题，我暂时没环境测试。能不能帮忙试试调整 https://github.com/cloudwu/stellaris_cn/blob/master/cn/interface/fonts.gfx. 这个文件看看是哪个字体影响。

试试改一下 vertical_offset 或 ttf_size 。
