### ISSUE TITLE
关于 station 的译法

### ISSUE THREAD

**Issue by cloudwu** [cloudwu/stellaris_cn#47]
现在游戏里的 station 基本都翻译成机站、站点，或 XX 站。但是重新读了很多文本，结合游戏里的图像表现，我觉得这里的 station 往往指的是一种很大的东西。

所以我觉得大部分地方改译成基地更合适。

尤其是防御设施里，防御平台 和 防御站 很难感觉出哪个更高级一些，如果翻译成防御基地就好一些了。

因为还有些战争诉求也和 station 有关，所以牵扯比较多。

@soarqin 能否结合这个做下一步的修正？

**Comment by soarqin** [comment]
如果是这样话，太空港(Spaceport)按照实际含义，我觉得或许可以改回去，补全为“轨道空间站”，因为之前我看上下文，就觉得Orbital Station大多数地方就是指Spaceport

**Comment by soarqin** [comment]
查了一下官方wiki的说明，Orbital Station就是指无人行星上的采矿站(现在翻译为采矿基地，感觉更舒服一点)，是我理解错了，看来Spaceport还是必须叫太空港

**Comment by cloudwu** [comment]
也不是所有的 station 都一定严格用一样的词的，英文版也不是这样。感觉还是按习惯来。

比如 `shipclass_orbital_station:0 "Spaceport"` 内部其实是把 spaceport 归为 station 类建筑的。outpost 的内部名也是 station 。例如，`war_demand_cede_frontier_outpost_no_stations_left:1 "星系中所有有站点的帝国都被完全吞并了"` 这句从 key 来看，其实是指的 frontier outpost ，英文写的就是 stations 。

**Comment by soarqin** [comment]
嗯，shipclass_orbital_station这个是我一开始推断Spaceport就是Orbital Station的一个原因，但是我看到wiki的mod说明里，还有reddit上的一些讨论里，主要把Orbital Station描述为无人行星上建造的各种Station

**Comment by soarqin** [comment]
frontier outpost在很多地方写的就是outpost station，包括wiki的名词解释里，本质上就是station没错

**Comment by Tianchenglipu** [comment]
Military Station 如果翻译成军事基地的话，会不会有点联想不到这是一个太空建筑

**Comment by soarqin** [comment]
@Tianchenglipu 毕竟是太空游戏，应该不难理解，叫做太空军事基地又太长了，叫太空堡垒的话那啥你懂的……

**Comment by epfte** [comment]
正在建造 军事站 1% 233

**Comment by epfte** [comment]
这游戏的图不要弄太大,一般中型就够了，玩起来用的时间太长。
