### ISSUE TITLE
2.0 翻译计划

### ISSUE THREAD

**Issue by cloudwu** [cloudwu/stellaris_cn#477]
这次 2.0 官方夹带了中文（但是没有暴露在界面上），我提取在了 https://github.com/cloudwu/stellaris_cn/tree/master/cn2.0  这个目录下，供参考。

这次，我打算在差异文件下开展工作，在初步翻译结束前，请大家不要直接在 cn 目录下修改文本。这个目录目前由我用脚本合并。这次需要翻译的工作，我用脚本提取在了 diff 目录下，请大家对 diff 目录下的文件进行翻译工作。

目前， diff 文件是采用以下规则提取：

1. 如果新旧英文文本完全没有变化，则保留原来的翻译。在 diff 文件中没有条目。
2. 如果新旧英文文本只有 key 有数字变化，则保留原来的翻译，在 diff 文件中有一条 CHANGE 开头的条目，内容是原来的旧翻译。
3. 如果条目只在新版本英文中出现，旧版本没有，则在 diff 文件中有 ADD 开头的条目，内容是新的英文文本。
4. 如果旧条目在新版本英文中删除，则在 diff 文件中有 RM 开头的条目。（通常不用理会）
5. 如果新旧英文文本不一致，则在 diff 文件中有 OLD 开头的英文条目表示旧文本；NEW 开头的英文条目表示新文本，CN 开头的条目，表示旧翻译。
6. 如果有新增的官方中文条目，diff 文件中会增加 CN2 开头的条目供参考。

目前我们需要做的是：

把所有 diff 文件中 ADD NEW 的条目翻译成中文，翻译的条目请用 CHANGE 开头。然后我会用工具合并到 cn 目录下。

注意，合并工具采用以下规则：

1. 如果发现 CHANGE 开头的条目，优先级最高，一定会替换为正式的正文翻译。
2. 如果发现 CN2 开头的条目，且没有 CHANGE 开头的条目，会用这个版本的翻译。
3. 如果以上都没有，但是英文条目已经发生变化，则会保留新版本的英文原文。
4. diff 文件没有提到的条目，会保留原来的中文翻译。

如果还有不明白的地方，请在本贴下提问。

**Comment by fqqdc** [comment]
赞，老大动作真快，我明天白天开始动手。

**Comment by cloudwu** [comment]
注：脚本我也上传了，可以自己玩，临时写的，比较乱。在 script 目录下，merge.lua 可以用于合并。跑脚本前最好备份 cn 目录，因为会改写。

先随便 at 下面同学，没 at 到的别生气，at 到的也别嫌骚扰 :)

@wzy9607 @fqqdc @inkitter @soarqin @syj2010syj @yaxu75 @BurningRainbow @mrgump @mo805241560 @EndlessOne @winnersun  @94kimisuke @Malory9 @zsc19921016

**Comment by EndlessOne** [comment]
长老世界？敌对部落？

建议使用正则匹配替换。

**Comment by cloudwu** [comment]
全局替换没问题。不过最好不改 CN2 条目，而是新建 CHANGE 条目，这样方便对照。

当然，操作上就比较麻烦了。

**Comment by cloudwu** [comment]
可以针对新名词讨论一下，列出来放在术语表，我来一起换掉。2.0 汉化初步完成后，再恢复直接修改 mod 文件的流程。

**Comment by cloudwu** [comment]
如果确定要使用过去的汉化条目（可能英文条目的修改只是修改英文的别字或大小写），那么直接把 CN 改成 CHANGE 也可以。

**Comment by winnersun** [comment]
收到，为了自己能尽快的爽玩，我会尽快开始^_^

**Comment by inkitter** [comment]
说实话。。。我之前写的程序翻译起来真的已经很顺手。。。用脚本提出来反而变得麻烦了T.T
三个版本对照、自动跳到未翻译的条目、外加百度和google全文翻译参考，自动补缺的引号。目前我发现的唯一的bug就是有时候会多补一对引号出来，是我写的正则表达式的缺陷。

**Comment by cloudwu** [comment]
空的 diff 文件已经初步校对完成的 diff 文件，我已经从 diff 目录删除。已删除 diff 对应文件的相关修改可以直接在 cn 下原文上做了。

另外 `l_english` 这个文件的初步校对我快速过了一遍，明天我也会删除对应 diff 文件。

如果那个同学把那些小的 diff 文件校对完毕，这里留个言，我也将合并并删除。

**Comment by cloudwu** [comment]
2.0 已经初步翻译完成，diff 目录我明天删除。（如果需要参考，可以自己 checkout 老版本）
接下来大家可以直接在 cn 目录下直接提交校对。

btw, 还有一个名词没有翻译：
```
ADD tech_embodied_dynamism:0 "Embodied Dynamism" #TODO
ADD tech_embodied_dynamism_desc:0 "Initiative and some measure of ambition must be promoted in our autonomous leader units, while still making certain that they do not stray too far from the directives of the core intelligence."
CHANGE tech_embodied_dynamism_desc:0 "在我们的自治部门中，我们鼓励主动精神和明确的目标，但同时需要确保他们不背离核心智能的指示。"
```

这个 Embodied Dynamism 我还没在游戏里看到，有玩到的同学给个建议？

**Comment by winnersun** [comment]
![image](https://user-images.githubusercontent.com/1186588/36721276-651c2064-1be5-11e8-9718-2d0938ebd51d.png)
应该是以前的那一系列影响力+1的科技中的一个，可以翻译为“高度自治”、“调动积极性”什么的。
@cloudwu

**Comment by cloudwu** [comment]
我重新翻译了一下这个词条：
```
ADD tech_embodied_dynamism:0 "Embodied Dynamism"
CHANGE tech_embodied_dynamism:0 "活力具现"
ADD tech_embodied_dynamism_desc:0 "Initiative and some measure of ambition must be promoted in our autonomous leader units, while still making certain that they do not stray too far from the directives of the core intelligence."
CHANGE tech_embodied_dynamism_desc:0 "只要能在核心情报机关的控制下不要过度迷失，我们应该多多提拔那些更有主动性，有点小野心的自治部门领袖。"
```

不知道有没有理解对。

**Comment by PolluxGlory** [comment]
好像是我的锅 _(:з」∠)_

**Comment by winnersun** [comment]
好像测试beta更新2.02了，要编个版本吗？改动挺大

**Comment by cloudwu** [comment]
明天我开个 2.02 分支，暂时不要把 2.02 的改动 pr 到 master .

**Comment by cloudwu** [comment]
2.0.2 分支已经建好，我已经搞定了大多数改动。`l_english` 里还有一点没有完成，请大家帮忙补全。

**Comment by winnersun** [comment]
beta2.0.2b
* Added event that lets countries with a Chosen One become a Divine Empire
北京时间3月6日22点，2.02更新了一下，加了事件

**Comment by winnersun** [comment]
utopia.3400.name

**Comment by zheng163616** [comment]
我在游戏中发现一些字的错误，比如星门的门字，变成日语中的汉字-门，我知道在UTF-8中这2个字共享U+95e8，是因为作者上传电脑的问题么？

**Comment by fqqdc** [comment]
这个是游戏自带的中文字体的问题，安装一个字体MOD换一个字体就好了。

**Comment by tmxkn1** [comment]
`ADD tech_embodied_dynamism_desc:0 "Initiative and some measure of ambition must be promoted in our autonomous leader units, while still making certain that they do not stray too far from the directives of the core intelligence."
CHANGE tech_embodied_dynamism_desc:0 "只要能在核心情报机关的控制下不要过度迷失，我们应该多多提拔那些更有主动性，有点小野心的自治部门领袖。"`

翻译不准确。这里的promote是指宣扬而不是提拔。

个人认为较准确的翻译应该是：
`我们应该在我们的自治领导框架内更多地宣扬主动性和一定程度上的野心。当然，前提是他们不能从我们的核心指导思想游离太远。`

不过在国外生活了好久，我的中文退化严重。我的翻译应该是精准的，但是通不通顺我就判断不好了xD

**Comment by fqqdc** [comment]
2.0.2的英文词条应该发生了增减变化

使用汉化补丁后，道德准则：完型意识、军国主义文本中出现了不存在的词条。而英文原版没有问题。

**Comment by cloudwu** [comment]
我这里没有看到这些。btw, 2.0.2 分支上还有一些没有翻译的位置，大家帮忙搞一下。具体差异可以看  https://github.com/cloudwu/stellaris_cn/pull/557

**Comment by cloudwu** [comment]
2.0.2 改动新增部分，大部分我都补上了，还剩下一些，大家帮个手 :) 我新开了一贴  https://github.com/cloudwu/stellaris_cn/issues/558
