### ISSUE TITLE
刚刚突然发现一个问题

### ISSUE THREAD

**Issue by yuan1238y** [cloudwu/stellaris_cn#51]
我发现在新建游戏，选择帝国的那里。
武器那里，质量加速器的翻译没了？？？
显示成了   tech_mass_drivers_1
我看了一下翻译文件没有问题啊
而且所有的都没了。
我只开了 翻译 字库 1080P 的MOD
这是什么情况？

**Comment by yuan1238y** [comment]
而且好多内容都没翻译了

**Comment by yuan1238y** [comment]
刚刚只保留字库以及翻译MOD看了
也是一样。
不开翻译MOD没事。
打开除开翻译MOD之外的其他MOD也没问题。
我也检查了编码，没发现问题啊！！

**Comment by cloudwu** [comment]
退一个版本看看。看是不是什么地方格式错了。

**Comment by cloudwu** [comment]
是不是 BOM 被改了？

**Comment by yuan1238y** [comment]
我检查了所有文件，BOM都是有的

**Comment by yuan1238y** [comment]
还有，中文字库也有点小问题，有的字显示不出来。
比如 瑞玵香料 的 玵 显示不出来

**Comment by cloudwu** [comment]
有 9 个文件的 BOM 被误删了，刚才加回去就好了。

玵可能没有放在字库里，我看看改个字好了。

**Comment by yuan1238y** [comment]
咦？我昨晚1点多同步到我的库里面的没问题啊

**Comment by cloudwu** [comment]
增加了个脚本检查是否丢失了 BOM ，以及是否用了字库里没有的字。

https://github.com/cloudwu/stellaris_cn/commit/26ebdc152575416c78ac6a082f432a6034e589f1

**Comment by yuan1238y** [comment]
这些会在游戏中执行？？？

**Comment by cloudwu** [comment]
自用。
