### ISSUE TITLE
我挖了一个深坑，打算翻译官方的wiki

### ISSUE THREAD

**Issue by fqqdc** [cloudwu/stellaris_cn#529]
与cloud wu的汉化mod为准，目前正在龟速填坑。刚刚填了一捧土，不知道热情能持续多久。
有兴趣参与的同学可以在下面留言，或者加我的QQ65026145。

地址：http://www.fqqdc.club/mediawiki/Stellaris_Wiki

**Comment by winnersun** [comment]
对这个wiki的源码十分感兴趣，请问网站的源码或者模板是从哪来的啊？

**Comment by fqqdc** [comment]
wiki用的源码是mediawiki，是开源的，很容易搜到它。

**Comment by cloudwu** [comment]
不搞 git 仓库挺麻烦的。

我对战争系统有兴趣。

**Comment by fqqdc** [comment]
我对具体的技术不太了解，wiki也只是勉强搭起来而已，有什么问题请指教一下。

**Comment by winnersun** [comment]
mediawiki自己就带的协作系统，好像没法用git控制

发自我的 iPhone

在 2018年3月13日，11:37，Emanon <notifications@github.com<mailto:notifications@github.com>> 写道：


我对具体的技术不太了解，wiki也只是勉强搭起来而已，有什么问题请指教一下。

**Comment by winnersun** [comment]
灰机wiki上已经有了一个群星的wiki，可以参考一下，那个使用了semantic wiki插件，可以把wiki变成数据库，实现多种查询和表格展示，挺有意思的

发自我的 iPhone

在 2018年3月13日，11:37，Emanon <notifications@github.com<mailto:notifications@github.com>> 写道：


我对具体的技术不太了解，wiki也只是勉强搭起来而已，有什么问题请指教一下。

**Comment by cloudwu** [comment]
如果格式转换容易，用 github 自带的 wiki 系统会比较容易协作。

**Comment by fqqdc** [comment]
灰机的群星wiki最大的问题是跟官网差别太大，使用了各种酷炫复杂的模板和css样式，对我这种新手门槛太高。

而且他们明显缺少人手维护，官网如果有更新，新手完全不知道该怎么修改。

他们使用的是贴吧汉化，大部分名词汉化后都不一样。

**Comment by fqqdc** [comment]
github的wiki么，有没有相关的文档？我想了解一下。

**Comment by fqqdc** [comment]
我随意看了一些资料， github 自带的 wiki 部分支持官方wiki(也就是mediawiki)的语法。人工转化过来工作量可以接受，但是官方的词条有很多图片，不知道github wiki该怎么管理图片。

**Comment by cloudwu** [comment]
就是下面 Styling with Markdown is supported 这个链接。语法要比 mediawiki 的样式少很多，但是基本够用。关键是可以 clone 到本地维护。github 可以直接贴图片，copy - paster 也可以。

**Comment by inkitter** [comment]
mediawiki 维护起来过于复杂，我认为不适合个人维护。如果有很多项目，最终就会弃坑。
我一直是使用dokuwiki，非常容易搭建和配置，所有文本都是plain text。它的缺点是性能比较差，人太多的话，服务器可能比较惨。
比如我已经不去更新一个游戏的wiki，用的doku，很省心： tpr.inkit.org。
管理SQL对业余的个人项目来说，实在是巨大的负担。。。
