### ISSUE TITLE
tutorial.560.desc 中一个神奇的句子

### ISSUE THREAD

**Issue by mengxy** [cloudwu/stellaris_cn#59]
> A new technology has revealed that we already have a §SMining Station§! conveniently placed above a previously unknown §SStrategic Resource§!. These rare resources are required to construct and operate unique §SBuildings§! and §SSpaceport Modules§!. **Two metaphorical avians, allegorically struck down by an imaginary projectile.**\n\nMore information can be found in the §SSituation Log§! for a time. There are many more §SStrategic Resources§! left to discover in the galaxy, so keep on researching!

直译就是两只隐喻意义的小鸟，被虚构的导弹寓言般击落

感觉就是用隐喻的说法来说之前建过的采矿基地又发现了新的资源，我想了两个中文类似的描述『一石二鸟』和『老树发新芽』，也都不是很合适，大家有什么想法？

**Comment by cloudwu** [comment]
一石二鸟，一箭双雕，都行吧。只是少掉了科幻意味。
