### ISSUE TITLE
Galaxy（星系） & System（恒星系）

### ISSUE THREAD

**Issue by tmxkn1** [cloudwu/stellaris_cn#596]
我在浏览翻译的时候看到不少地方都把 `Galaxy` 翻译为 `银河`，然而银河容易让人误解为银河系(Milky way)，这显然不是游戏里`Galaxy`的意思。

建议把`Galaxy`翻译为`星系`，而`System`为`恒星系`。

**Comment by cloudwu** [comment]
银河挺好的。

**Comment by menchian** [comment]
Galaxy 指的是“星系”，泛指大量恒星系聚集起来的系统

Milky Way 则是一个地名，一般是翻译成“银河系”或"银河"，指的是地球跟太阳系所在的Galaxy

我在校对时发现许多翻译有这个误用，且几乎所有的System都被翻译成应该是Galaxy的"星系"，因为工作量实在太大，我迟迟没有动手。

**Comment by cloudwu** [comment]
Galaxy 在英语里通常也指地球所在的星系。而星系在汉语语境里歧义也很多。银河放在游戏文本的语境中并不干扰游戏。

**Comment by EGZJY** [comment]
Galaxy Map (&M)

2018-05-10 7:32 GMT+08:00 云风 <notifications@github.com>:

**Comment by EGZJY** [comment]
Solo System... Solo Galaxy ? ..ON NO

**Comment by EGZJY** [comment]
改成 &System（我没意见）很棒

2018-05-10 8:50 GMT+08:00 Eg Zhongjian <eg.zhongjian@gmail.com>:

> Solo System... Solo Galaxy ? ..ON NO
>

**Comment by wzy9607** [comment]
`system`我校對的時候遇到的都改成`恆星系`了

**Comment by tmxkn1** [comment]
## Galaxy

从科学意义上来说，现代的galaxy就是指星系，而银河(系)则是Milky Way (Galaxy)。在过去，galaxy，特别是*G*alaxy，可以单指银河系。

以上这点是根据[Merriam Webster](https://www.merriam-webster.com/dictionary/galaxy)网络词典而写的。虽然词条的第一个解释即时银河系，但是你往下看到*Did you know?*，它说：

> ... Galaxias, the Greek word for the Milky Way, was derived from the Greek gala, “milk.” **English galaxy**, derived from Greek galaxias, was not used until the 19th century as a generic term for other star systems as well as the one in which we live.

这里指出了，**G**alaxy对应希腊语中的银河系，但是19世纪后，英语中的galaxy则被用作是广泛意义上的星系。

---

再看下[Oxford Dictionary的词条](https://en.oxforddictionaries.com/definition/us/galaxy)，其中的第二个解释为银河，给出的example中galaxy不是Our galaxy就是the galaxy。我臆测，若是the galaxy，根据英语的习惯，一定是前文已经出现了Milky Way，而后文则直接用the galaxy代替Milky Way了。

## System

这里首先纠正我一个科学错误。System有[plantary system](http://planetary-science.org/planetary-science-3/planetary-astronomy/)和star system，分别指是行星系和恒星系。而我们的太阳系或是游戏里的众多System，其实是指行星系。恒星系是多恒星组成的系统，而galaxy是一种庞大的恒星系。

相对于英文中galaxy的相对模糊的意义，中文的[星系](http://cd.hwxnet.com/view/cbjfoibmdganidbg.html)的意义则很纯粹，指大量恒星因为引力形成的天体系统，对应英文中的galaxy。游戏中出现的system很显然不是指上述的星系，而是指由行星围绕恒星组成的行星系，所以把system翻译为星系是绝对错误的。

**Comment by tmxkn1** [comment]
从科学意义上来说 galaxy就是指星系，而银河则是Milky Way Galaxy. 不过通俗来讲，在非常不正式的情况下，galaxy 特别是*G*alaxy，也是可以理解为银河的。可是游戏里语境中的system则完全不能理解为星系，一定是太阳系。星系在中文里有非常明确的意思，对应的就是英文里的galaxy。

**Comment by cloudwu** [comment]
根据维基百科 https://zh.wikipedia.org/wiki/%E6%98%9F%E7%B3%BB  对星系的解释

> 星系（英语：galaxy），或译为银河，源自于希腊语的“γαλαξίας”（galaxias）。

此处主要是放在游戏语境中看是否对玩家理解有困恼。我认为把 galaxy 译为银河，把 system 译为星系，对理解游戏概念更简洁无歧义。所以我也不喜欢强调 恒星系 的译法，比如围绕黑洞的 system 就不适合叫恒星系。

比如类似的翻译例子，在我们这套翻译文本的语境中，就没有把 corvette 翻译成词典上的 轻型护卫舰，而是直接翻译成 护卫舰。因为这样更简洁明了。也没有造成游戏概念的混淆。

采取这种译法也有一定的成例。比如星球大战系列（电影/小说）在中文语境中一直也是把 galaxy 翻译成银河，其实它并不指包含太阳的那个星系。galaxy 的词源希腊语中本就是指的银河，在日语中 galaxy 翻译成 **銀河** 也是一贯译法。银河本来就有特指太阳所在的星系和泛指星系的含义。

**Comment by tmxkn1** [comment]
### 关于黑洞

黑洞是由一颗恒星演变而来的，其引力巨大，按照科学来讲不应该会像游戏这样分布在星系之中，存在于各个行星系统之间，而应该会形成一个新的星系。所以，把黑洞翻译为行星系统/恒星系统也的确颇为不妥，不过黑洞在这个游戏里存在的方式本来就已经有违科学了。

由于游戏本身也存在不科学性，我们似乎也很难科学翻译出system。所以，这种看来，维持现状也许是唯一选择，我也认同cloudwu说的：

>此处主要是放在游戏语境中看是否对玩家理解有困恼。

游戏、文学、影视作品中为了娱乐的效果，牺牲了一定的科学性。不过也正是这些牺牲，造成了概念的模糊，导致一些词被习以为常地曲解了。不过，换个角度来想，并不是所有人都需要明确这些科学概念，需要明确这些科学概念的人，也许也并不会因为这些娱乐性质的作品而被误导。

### galaxy的维基百科

我当时也是一眼看到了维基百科上的这个说法。但是我又立刻查看了银河的维基百科，然后就变得非常困惑了。银河的百科上明确说了银河就是银河系，并没有任何一点说到泛指其他星系。所以，我才去从字典里查看了galaxy和银河，然后明确了这两个词。维基百科并不能作为一个权威的reference，毕竟你不能确定这些词条的编写者是否权威，也许是某个普通太空迷写的，而他本身对于这些概念就不是特别明确。虽然关键性的句子都是有引用的，但也许因为断章取义，导致读者无法得到一个全面的理解。

然后其他语言对于galaxy或银河的理解并不和英中有可靠的相关性，所以我认为只能作为参考而不能作为最后的判断依据。

**Comment by cloudwu** [comment]
我没意见。

**Comment by EGZJY** [comment]
Ok~Ok~

2018-05-11 20:38 GMT+08:00 云风 <notifications@github.com>:

**Comment by EGZJY** [comment]
这俩不管也可以因为我看惯了abc

2018-05-11 22:27 GMT+08:00 Eg Zhongjian <eg.zhongjian@gmail.com>:

**Comment by mahatlili** [comment]
galaxy以前有个专有名词译法叫河系，但貌似现在不怎么用，可能会误解为河流系统；当galaxy译为河系时，system译为星系没问题。偶然发觉GITHUB可以参与线上合作翻译，愿略尽绵力。我是塞爱维文明论坛的资深汉化者，参与过4，5，Beyond Earth，6的汉化；也是科幻小说的业余译者。 @cloudwu

**Comment by tmxkn1** [comment]
[**@mahatlili**](https://github.com/mahatlili) commented on [Jun 2, 2018, 7:34 PM GMT+1](https://github.com/cloudwu/stellaris_cn/issues/596#issuecomment-394107461 "2018-06-02T18:34:51Z - Replied by Github Reply Comments"):
> galaxy以前有个专有名词译法叫河系，但貌似现在不怎么用，可能会误解为河流系统；当galaxy译为河系时，system译为星系没问题。偶然发觉GITHUB可以参与线上合作翻译，愿略尽绵力。我是塞爱维文明论坛的资深汉化者，参与过4，5，Beyond Earth，6的汉化；也是科幻小说的业余译者。 [@cloudwu](https://github.com/cloudwu)

Welcome!!

**Comment by cloudwu** [comment]
欢迎。目前在翻译遥远群星 dlc 事件，对过去文本校对也欢迎，可直接提 pr 。

**Comment by egzhongjian** [comment]
你微博被封了？

2018-06-03 8:13 GMT+09:00 云风 <notifications@github.com>:

**Comment by cloudwu** [comment]
封了 👍 在不可提及的日子谈及了不可说的事情。不知道是关几天小黑屋还是被杀无赦了。
