### ISSUE TITLE
xxx (project name), available

### ISSUE THREAD

**Issue by tmxkn1** [cloudwu/stellaris_cn#603]
![image](https://user-images.githubusercontent.com/8778250/40282776-0800956e-5c6c-11e8-9fc1-9e476222bcc2.png)

available翻译为“可用”，是不是有点不太合适？也许可以翻译为“有效”？

 > SPECIAL_PROJECT_STATUS_AVAILABLE:0 "可用"
 SPECIAL_PROJECT_STATUS_UNAVAILABLE:0 "不可用"

**Comment by cloudwu** [comment]
可完成，可进行 ？
不可完成，无法进行。

**Comment by tmxkn1** [comment]
感觉可进行会比较好

**Comment by wzy9607** [comment]
已經改成可研究、无法开始了。
