### ISSUE TITLE
2.1 汉化计划

### ISSUE THREAD

**Issue by cloudwu** [cloudwu/stellaris_cn#605]
这次和 2.0 一样，我们还是先在 diff 文件夹工作，不要直接翻译原文。具体规范见 #477 。有本次版本的问题在本贴讨论。

**Comment by wzy9607** [comment]
guardian_l 2.1重命名作leviathans同時guardian_l和apocalypse中所有guardian開頭條目重命名作了leviathans。

**Comment by wzy9607** [comment]
leviathans的diff需要重新處理一下

**Comment by wzy9607** [comment]
另外distant_stars_l_english漏了。

**Comment by cloudwu** [comment]
麻烦你弄一下了，我今天和明天出差。我先把 pr 合并。diff 的 merge 工作等我出差回来搞。

**Comment by wzy9607** [comment]
#608 diff补上了。

**Comment by wzy9607** [comment]
新名詞Nanite
舊與nanobot（部分）同譯作「纳米机器人」。
舊有Nanite
https://github.com/cloudwu/stellaris_cn/blob/17994c9ee8af853e88c603fc802d828e68d546a0/cn/localisation/english/events_l_english.yml#L1015
https://github.com/cloudwu/stellaris_cn/blob/17994c9ee8af853e88c603fc802d828e68d546a0/cn/localisation/english/events_l_english.yml#L1020
https://github.com/cloudwu/stellaris_cn/blob/17994c9ee8af853e88c603fc802d828e68d546a0/cn/localisation/english/events_l_english.yml#L1023
https://github.com/cloudwu/stellaris_cn/blob/17994c9ee8af853e88c603fc802d828e68d546a0/cn/localisation/english/technology_l_english.yml#L1087-L1088

舊有nanobot
https://github.com/cloudwu/stellaris_cn/blob/17994c9ee8af853e88c603fc802d828e68d546a0/cn/localisation/english/l_english.yml#L8115
https://github.com/cloudwu/stellaris_cn/blob/17994c9ee8af853e88c603fc802d828e68d546a0/cn/localisation/english/l_english.yml#L8468-L8470
https://github.com/cloudwu/stellaris_cn/blob/17994c9ee8af853e88c603fc802d828e68d546a0/cn/localisation/english/technology_l_english.yml#L264
https://github.com/cloudwu/stellaris_cn/blob/17994c9ee8af853e88c603fc802d828e68d546a0/cn/localisation/english/technology_l_english.yml#L619
https://github.com/cloudwu/stellaris_cn/blob/17994c9ee8af853e88c603fc802d828e68d546a0/cn/localisation/english/apocalypse_l_english.yml#L23
https://github.com/cloudwu/stellaris_cn/blob/17994c9ee8af853e88c603fc802d828e68d546a0/cn/localisation/english/apocalypse_l_english.yml#L55
https://github.com/cloudwu/stellaris_cn/blob/17994c9ee8af853e88c603fc802d828e68d546a0/cn/localisation/english/apocalypse_l_english.yml#L385-L386

**Comment by cloudwu** [comment]
除了新增加的  distant_stars_l_english ，其它的 diff 似乎已经处理完了。我把 diff 目录删除，以后就直接在原文修改吧（包括 distant_stars_l_english）。

**Comment by mengxy** [comment]
I am in this version.

**Comment by mengxy** [comment]
I am working on 'Anomaly Categories' in distant_stars.

**Comment by cloudwu** [comment]
同学们，日拱一卒啊，慢慢就翻译完了。这次的事件都是分离的，很适合一点点分开做。
https://github.com/cloudwu/stellaris_cn/blob/master/cn/localisation/english/distant_stars_l_english.yml

@wzy9607 @fqqdc @inkitter @soarqin @sumneko @PolluxGlory @yaxu75 @tmxkn1 @BurningRainbow  @EndlessOne @mrgump @mo805241560

**Comment by wzy9607** [comment]
發現河外星系
https://github.com/cloudwu/stellaris_cn/blob/19300f74365835e8fcab04313eb0c90a2511eb73/cn/localisation/english/distant_stars_l_english.yml#L301-L313

翻譯成「相邻銀河」？

**Comment by tmxkn1** [comment]
相邻银河 +1

**Comment by wzy9607** [comment]
船名Kohtalo待翻譯，似爲芬兰語「命運」。
https://github.com/cloudwu/stellaris_cn/blob/8049a43693eeb8965ee672bf93908bd028ca0d48/cn/localisation/english/distant_stars_l_english.yml#L300

**Comment by wzy9607** [comment]
待翻譯人名Reth Unddol，語源未知。

**Comment by cloudwu** [comment]
Reth Unddol 的 Reth 我猜想可能来源于 https://en.wikipedia.org/wiki/Paranormalcy 这本奇幻小说，Reth 是一个挺厉害（正邪摇摆）的精灵。

Unddol 看起来是造出来的词。  und- 看起来有未知的意思，-dol 有痛苦的意思。

**Comment by wzy9607** [comment]
Reth有可能來自蘇格蘭方言，(of persons) Fierce; cruel; savage; stern; zealous; ardent; keen，音譯「銳斯」？
https://en.wiktionary.org/wiki/rethe

**Comment by zl1271** [comment]
把灵能宠物老鼠种族「Ketling」简单音译成了「卡特林」，因为并没有查到明显的梗出处。
https://github.com/cloudwu/stellaris_cn/blob/fc2478163c159c7ea8ccf4ccbeedb13f1293631d/cn/localisation/english/distant_stars_l_english.yml#L818-L820

不过他们在事件链的注释里的名字叫「Ratlings」，可以搜到似乎是战锤 40k 里的一个种族。但那是个人形种族，而群星这个事件链里面是个鼠形宠物种族。
https://github.com/cloudwu/stellaris_cn/blob/fc2478163c159c7ea8ccf4ccbeedb13f1293631d/cn/localisation/english/distant_stars_l_english.yml#L643

**Comment by cloudwu** [comment]
Ratlings 就是鼠人吧？

**Comment by zl1271** [comment]
@cloudwu 有道理。不过还是想不出 Ketling 有啥音义兼备的译法……

**Comment by tmxkn1** [comment]
凯特琳鼠人 凯鼠人 灵能鼠人

**Comment by zl1271** [comment]
@tmxkn1 凯灵鼠人如何？

**Comment by zl1271** [comment]
神秘空腔 -> 神秘空管？
https://github.com/cloudwu/stellaris_cn/blob/47b215d607352053a8d0b18d89da5abd0d974dbd/cn/localisation/english/distant_stars_l_english.yml#L1254-L1267

这个事件组应该是致敬《与拉玛相会》，一个神秘的巨大管状物体突然来访。当然原著里是个密封的管子，而游戏里看模型是两头开口的。
之前翻译的这位用了“神秘空腔”，然而“腔”字给人描述有机生物体的感觉，虽然也能用来形容器物。
http://www.zdic.net/z/22/js/8154.htm
从游戏模型以及文本，以及拉玛原著来看，似乎应该是个机械/金属物体，也许用“神秘空管”更为合适。

**Comment by wzy9607** [comment]
话说这个issue该关了吧....
