### ISSUE TITLE
遗漏的英文文本

### ISSUE THREAD

**Issue by fqqdc** [cloudwu/stellaris_cn#617]
我发现的是在traditions_l_english.yml文件的187行附近。不清楚其他地方有没有类似的情况。

很多都是以前版本翻译过的，现在都是英文，而且和en的文本不一致，在diff对应的文件中也没有相应的内容。

**Comment by wzy9607** [comment]
l_engnlish, name_list也有，估計是merge腳本的bug。
https://github.com/cloudwu/stellaris_cn/commit/a32a69f19f994d52db1e7dee7ac82a658f3011e9#diff-fddfc856f5d5e8bfdf88924f12770a0fR5222
https://github.com/cloudwu/stellaris_cn/commit/a32a69f19f994d52db1e7dee7ac82a658f3011e9#diff-5def7b50dbb7ea14b2a62420ae7c08c8R316
https://github.com/cloudwu/stellaris_cn/commit/a32a69f19f994d52db1e7dee7ac82a658f3011e9#diff-69ca47aeeaf9f798b29c8daf81ca341eR187
https://github.com/cloudwu/stellaris_cn/commit/a32a69f19f994d52db1e7dee7ac82a658f3011e9#diff-fddfc856f5d5e8bfdf88924f12770a0fR8931

**Comment by wzy9607** [comment]
#618 
除 https://github.com/cloudwu/stellaris_cn/commit/a32a69f19f994d52db1e7dee7ac82a658f3011e9#diff-fddfc856f5d5e8bfdf88924f12770a0fR5222 外均解決了。

**Comment by fqqdc** [comment]
@cloudwu 能更新一下steam的MOD版本吗，一些内容出现在主要UI上，很影响游戏
