### ISSUE TITLE
以防止被激活/无法被激活/阻止其被激活

### ISSUE THREAD

**Issue by tmxkn1** [cloudwu/stellaris_cn#632]
相关词条：

https://github.com/wzy9607/stellaris_cn/blob/eb6068b07b53fde3ced872e3ee81f4635b280114/cn/localisation/english/apocalypse_l_english.yml#L412

> it has been deliberately locked into some kind of maintenance loop that prevents its activation
但它已经被故意锁定在某种维护回路中，以防止被激活

这句话中没有to/for等表达目的的词，that仅仅是一个代词，i.e.

*it has been deliberately locked into some kind of maintenance loop; this loop prevents its activation.*

所以，我以为翻译为**……，以防止被激活**不妥当。我先前提出的翻译是**……，无法被激活**，也不是很好。也许可以直接翻译为**……，阻止其被激活**？

@wzy9607

**Comment by cloudwu** [comment]
但它被故意锁定在某种维护回路中而无法启动

我觉得这样比较符合汉语语法。

**Comment by wzy9607** [comment]
改掉了
https://github.com/cloudwu/stellaris_cn/pull/631/commits/e233d5da78ebb43fe0b2a439dde4d3f191711b4b#diff-28868746a4fd123be4ae1b0f760d5f0bR412
