### ISSUE TITLE
翻译任务：无极机器

### ISSUE THREAD

**Issue by cloudwu** [cloudwu/stellaris_cn#64]
https://github.com/cloudwu/stellaris_cn/blob/master/cn/localisation/guardian_l_english.yml#L463-L535

这些是关于  Infinity Machine 的部分，译名想到更好的可以换。

**Comment by soarqin** [comment]
特别行动那边有人领了，我就翻这个吧，这个比较长，加上审校的时间估计一晚上不够
顺便说一句，贴吧汉化这个叫做无限神机，其实也不太舒服。看了一下英文部分，这个机器是在持续计算着关于“无穷/无尽”的一个悖论，所以可能叫无穷机器或者无尽机器比较好。
