### ISSUE TITLE
翻译任务：神秘要塞

### ISSUE THREAD

**Issue by cloudwu** [cloudwu/stellaris_cn#66]
https://github.com/cloudwu/stellaris_cn/blob/master/cn/localisation/guardian_l_english.yml#L553-L617

**Comment by cloudwu** [comment]
最后这段谁来搞搞 :)

**Comment by zsc19921016** [comment]
我来吧，大概明天晚上能好

**Comment by cloudwu** [comment]
已经是最后一段了 :D
