### ISSUE TITLE
push的时候出警告

### ISSUE THREAD

**Issue by mahatlili** [cloudwu/stellaris_cn#673]
大意是认证失败，没有许可进入repository blabla。github还是对我等编程小白不友好啊。 用的是win客户端

**Comment by zl1271** [comment]
遇到过，是 SSH key 吗？我是参考官方的说明搞好的
https://help.github.com/articles/connecting-to-github-with-ssh/

**Comment by mahatlili** [comment]
Authentication failed. You may not have permission to access the repository or the repository may have been archived. Open options and verify that you're signed in with an account that has permission to access this repository.
@zl1271

**Comment by mahatlili** [comment]
我上一次push还是OK，今天发生的问题可能是我pull之后翻译了一段，期间老大commit了一次更新，然后我想push的时候显示同时有1个push request 和1个pull request然后当我pr后，自动跳到浏览器页面要我compare，然后我看更新的和我翻译的不冲突，也不知道按什么，然后关掉页面，再次pr就反复出现上述Error Warning

**Comment by cloudwu** [comment]
认证失败看起来是没登录。我没用过那个图形化客户端，git 还是命令行的好用。

你的工作都是在你自己的 fork 上做的，所以上游改变都不会影响你自己的 push 。除非你想直接 push 到上游（我这个），那当然是没权限的。

**Comment by zl1271** [comment]
@mahatlili 按道理讲 Windows 上用客户端是不会出现这登录失败的提示的，但用命令行会，这时候就需要先按我给的那个链接生成一下 SSH Key 然后复制到 Github 帐号里。
不过我也是新手，经常遇到各种问题，最后没办法了就手动把修改拷出来备份，然后 hard reset，或者干脆全删了重新弄。

**Comment by mahatlili** [comment]
全部删除，重新fork,clone, pr，现在能上传了，但是把我做过的全部内容和之间别人更新的部分内容也包括进去了，我也不懂为什么。希望下次别出新的状况；我花在研究GITHUB客户端的事件，比翻译的时间还多。

**Comment by cloudwu** [comment]
严格按 workflow 文档里命令行操作，尤其是用 reset 应该不会出问题。
