### ISSUE TITLE
准备翻译1218行#hatchling Leviathan 及相关条目

### ISSUE THREAD

**Issue by mahatlili** [cloudwu/stellaris_cn#679]
包括以下关键词 Rift seismlogy voidspawn。预计时间1-2天，请看到的同学尽量避免撞车，谢谢。

**Comment by cloudwu** [comment]
今天晚上 P 社更新了 2.1.1b ，请务必 merge 一下主干再继续工作，避免文本不一致。

**Comment by mahatlili** [comment]
完成，关话题
