### ISSUE TITLE
翻译任务：无畏战舰

### ISSUE THREAD

**Issue by cloudwu** [cloudwu/stellaris_cn#68]
https://github.com/cloudwu/stellaris_cn/blob/master/cn/localisation/guardian_l_english.yml#L632-L641

**Comment by weiwei2012start** [comment]
无畏战舰
一个巨型的战船被发现并且正在巡逻[dreadnought_system.GetName]系统
在船内没有生命的迹象被检测，但是散发出强壮的力量记号和出现竖着的武器系统，它没有对冰雹做出反应。注意安全
看看这个战舰的大小
无畏战舰伤残了
我设法吹残无畏战舰在 guardians_dreadnought_system.GetName]系统
尽管惩罚来自我们的船，战舰的巨大船体的结构完整性在很大程度上仍然完好无损
我们的寄宿者发现木乃伊的无畏战舰的外籍船员仍在操纵台。  （不知道怎么翻译好）
到期前，他们激活了某种自动化的巡逻模式，限制舰载AI已被锁定在过去的780万年。
虽然它会花费令人不可想象的大量资源
我们的一些工程师认为，无畏战舰可以恢复并重新为我们的舰队服役。它肯定会成为一个强大的旗舰
这首船将会在我们的操作下在航行在星空
也许是浪费资源，我们的一个船员说
无畏战舰修好了
这是重大的一天
我们的技术修好了船员和工程师完成了他们的工作并且古代的无畏舰我们禁用了这个系统上 [guardians_dreadnought_system.GetName]
这艘巨大的战舰已经得到了充足的船员补充,并已宣布准备进行太空试验后的服务
一个强大的力量加入到我们的舰队

四级没过的人尝试下

**Comment by cloudwu** [comment]
可以提个 pr 吗？放在这里很难合并和审校。
