### ISSUE TITLE
2.1.3 汉化召集

### ISSUE THREAD

**Issue by cloudwu** [cloudwu/stellaris_cn#697]
2.1.3 主要修改了  Distant Stars DLC 的一些事件，见：

 https://github.com/cloudwu/stellaris_cn/commit/8fcfc8a105e3c8b17ae1438652fd42fd9bccf2d8

大家帮忙一起翻译一下。

**Comment by cloudwu** [comment]
目前待译条目：

* [ ] https://github.com/cloudwu/stellaris_cn/blob/master/cn/localisation/english/distant_stars_l_english.yml#L2049-L2133
* [ ] https://github.com/cloudwu/stellaris_cn/blob/master/cn/localisation/english/distant_stars_l_english.yml#L2450-L2587

**Comment by wzy9607** [comment]
L2049-L2133我應該明天能翻好。

**Comment by zl1271** [comment]
那我今晚翻一些 L2450 开始的，不过肯定翻不完

**Comment by cloudwu** [comment]
minds 我觉得翻译成思想/心智 更好，深邃好像比遥远更贴切一些。

**Comment by cloudwu** [comment]
另外我觉得作为专有名词，不用刻意的把每个意思都翻译出来导致名词到中文变成一长串，这不太符合中文的用语习惯。我个人觉得，far 可以省略。比如就叫 凯灵心智 凯灵智慧 或 凯灵之心 就可以了。

**Comment by wzy9607** [comment]
我建議从Far-Minds的翻譯中把凱靈刪了，譯成「深幽心智」之類。

**Comment by zl1271** [comment]
综合两位，先这样：少数我觉得说长串更顺口的地方用「深幽的凯灵心智」，简称更顺口的地方「凯灵心智」。
仔细想想我感觉「心智」大概比「之心」更好，鼠人帝国游戏里的设定没记错的话好像是种族特性带灵能，但思潮是物质主义，「之心」感觉过于精神了。
我不喜欢全部按意思严格直译为「深幽心智」的原因是中文毕竟没有专有名词大写，用特殊的名字（「凯灵」）更能让玩家看明白这是鼠人自称。
当然都是个人意见，水完这波翻译我就消失了……润色还是靠你们。
