### ISSUE TITLE
翻译任务：特别行动

### ISSUE THREAD

**Issue by cloudwu** [cloudwu/stellaris_cn#70]
https://github.com/cloudwu/stellaris_cn/blob/master/cn/localisation/guardian_l_english.yml#L659-L693

**Comment by soarqin** [comment]
今天我翻一下这个部分，看起来这个部分和其他几个部分有关联，不过因为MISC里也都有关联，我都翻过了，应该问题不大

**Comment by zsc19921016** [comment]
昨天看到没人留言就挑了这一部分。提了pr发现被认领了_(:з」∠)_

**Comment by soarqin** [comment]
我还没开始翻译，你提交PR吧
