### ISSUE TITLE
利维坦 DLC 文本拆分翻译需求

### ISSUE THREAD

**Issue by cloudwu** [cloudwu/stellaris_cn#71]
我大概把利维坦 DLC 的未翻译文本内容拆分成 10 个部分，希望各位同学积极认领翻译。见 issue 区的分贴。有兴趣的同学可以直接在独立的帖子里回复，避免冲突。

拆分后，每个都相对不多，翻译起来，工作量也就没那么可怕了。

**Comment by soarqin** [comment]
后面还有一段#MISC和任务相关的建筑物没有放一条单独的issue，我先把这个部分做了吧，因为这个部分好像出现频率比较高，特别是完成特别任务后家里增加的建筑物

**Comment by cloudwu** [comment]
https://github.com/cloudwu/stellaris_cn/blob/master/cn/localisation/guardian_l_english.yml#L411-L425

要不把这小段搞定？
