### ISSUE TITLE
2.2 汉化（校正）

### ISSUE THREAD

**Issue by wzy9607** [cloudwu/stellaris_cn#712]
12月6日上線的2.2要正式加入官中了，~~多半還是部落打仗~~。現在可以先討論討論術語的翻譯了。

**Comment by wzy9607** [comment]
District：地区（现文本存在少量冲突）
* City District：都市地区
* Farming District：农业地区
* Mining District：采矿地区
* Generator District：发电（？）地区
Job：工作
Housing：住房
Devastation：
Amenity：舒适度
Empire Cohesion：
Empire Development：帝国发展度
Civic
Shared Burden：同甘共苦（？）
Byzantine Bureaucracy：复杂官僚（？）
Living Standard：
* Stratified Economy ：
Ascension Perk
* Arcology Project：生态建筑（？）工程
* Hive Worlds：蜂巢世界
* Xeno-Compatibility：异族兼容（？）
* Universal Transactions：寰宇交易
Tech
* Resort Worlds：度假星球（？）
Empire type
* Megacorporation：巨型企业（沿用）
势力
* Caravaneer：篷车商（？）
Megastructure
* Matter Decompressor：
* Mega-Art Installation：
* Interstellar Assembly：
* Strategic Coordination Center：
Market
* Galactic Market：银河市场
* Slave Market：奴隶市场
* Internal Market：国内市场（？）
trade route：贸易路线

**Comment by cloudwu** [comment]
我先改良一下合并脚本，为官中发布做准备。这次打算按以下规则：

1. 如果英文条目不变，就直接使用原始翻译，无论是否官中有翻译。
2. 如果是新增条目，把官中搬过来，并暂注 “[官中]:” 标签，等待人工审核。如果官中漏翻，就保留英文。
3. 如果是英文条目发生变化，把官中放在差异文件中，继续保留原始翻译，但加注 "[待校]:" 标签。

**Comment by cloudwu** [comment]
Overcrowding : 人满为患

**Comment by wzy9607** [comment]
中午看了眼游研社的直播，官汉和谐内容应该比2.0少（至少不是船队了）。

另外District翻译成区域的话和现有文本冲突比较大，行星的部分、星系的部分、银河的部分都有用区域称呼的。不过tile blocker的描述中区域用的也比地区多。

**Comment by cloudwu** [comment]
目前还是推荐在 diff 目录工作。cn 目录目前提供了两个一样的版本，对应在游戏里选择英文和中文。这是因为目前选中文版有时候会闪退；选英文版就没有了中文名字。

这两个版本都是脚本自动生成，所以暂时不要在上面直接修改。

**Comment by cloudwu** [comment]
github 上 simpl_chinese 删掉了，需要的同学可以自己用 script/simpc.lua 生成。以后只维护 english 目录。

**Comment by wzy9607** [comment]
- [ ] messages待统一语言风格（合并后）

**Comment by wzy9607** [comment]
合併後工作

- [ ] messages待统一语言风格

- [ ] 危機的相關名詞（見terms_list）待統一

**Comment by cloudwu** [comment]
注意：现在的图标语法，P 社程序实现有 bug ，有时候 ￡ 后面紧接汉字有可能触发 bug 导致程序闪退。比如官方版本的 建造巨构建筑 按钮按下闪退就是这个引起的。所以在确认没问题前，最好所有图标后都加一个空格回避。

**Comment by fqqdc** [comment]
官方中文把xxx Jobs翻译成"xxx职业"，游戏中我感觉翻译成"xxx岗位"更合适。

**Comment by cloudwu** [comment]
综合一下，是不是用职位比较好。

**Comment by wzy9607** [comment]
正式文本沒有用deposit，用的Planetary Feature，考慮譯成行星地貌。

**Comment by menchian** [comment]
职位的 Drones 部份（如：Tech-Drone、Agri-Drone），因在游戏中确确实实占用了人口数，如果还是翻译成无人机是否妥当？

**Comment by wzy9607** [comment]
Drone好像是蜂群用的，那样应该译作工蜂。

**Comment by wzy9607** [comment]
我正在校对districts。

**Comment by cloudwu** [comment]
今天又发现一个图标 bug ，参考 feature_robots_desc 词条，£pop_cat_worker£ 前后空格都不能省略，否则游戏中会显示成问号。 推测和紧接着的 §Y$pop_cat_worker$ 有关。

可能是 P 社为了英文显示漂亮，自己吃掉了后面的空格字符，不留空格反而出错。

**Comment by wzy9607** [comment]
每行的長度與分辨率有關，在我這（1080）feature_robots_desc那行沒有空格也不會引起bug。

**Comment by wzy9607** [comment]
只要在圖標前面加個空格就可以了（會導致其它分辨率下亂換行）。

**Comment by wzy9607** [comment]
feature_robots_desc那行長度我調整了。

**Comment by wzy9607** [comment]
#721 最後兩個實際上也是這個bug。

**Comment by wzy9607** [comment]
我在校对tradition，tutorial大部分还没动过，l_english从policy_population_controls_desc开始还没动过。

**Comment by wzy9607** [comment]
可以merge刪diff了，~~我已經在修自己merge後的原文了~~。

**Comment by cloudwu** [comment]
diff 已删除，接下来接收对原文的修改。我另外创建 2.2.2 的分支合并 beta 分支。

**Comment by wzy9607** [comment]
测试了一下，巨构建筑建造界面的bug2.2.2修复了。
