### ISSUE TITLE
提交一些bug

### ISSUE THREAD

**Issue by fqqdc** [cloudwu/stellaris_cn#721]
![20181208162431](https://user-images.githubusercontent.com/365449/49684497-a3716900-fb0f-11e8-9d66-9793d3e35ae2.png)
![20181208163734](https://user-images.githubusercontent.com/365449/49684498-a3716900-fb0f-11e8-8e6a-a5b4ffc6f804.png)
![20181208170547](https://user-images.githubusercontent.com/365449/49684499-a3716900-fb0f-11e8-85d7-3bee49a1b9ac.png)
![20181208171824](https://user-images.githubusercontent.com/365449/49684500-a409ff80-fb0f-11e8-8c12-82c9d6c3c401.png)
![20181208172607](https://user-images.githubusercontent.com/365449/49684501-a409ff80-fb0f-11e8-83c0-f1c83f3acef5.png)
![20181208153457](https://user-images.githubusercontent.com/365449/49684502-a4a29600-fb0f-11e8-8ea5-fc2bfb6f8673.png)
![20181208162239](https://user-images.githubusercontent.com/365449/49684503-a4a29600-fb0f-11e8-80a4-41f2889a1e19.png)

**Comment by wzy9607** [comment]
2、3我在 #719 修了，1、4、5我在#720 （还没merge）补上了。
看了一下cn目录没有更新。

**Comment by cloudwu** [comment]
#720 有大量非 diff 提交，需要修正一下，把对应 diff 提交。目前所有 .yml 都靠脚本生成，不要人工修改。
