### ISSUE TITLE
2.3.1 UI出现很多上的字符串的错误

### ISSUE THREAD

**Issue by fqqdc** [cloudwu/stellaris_cn#755]
![image](https://user-images.githubusercontent.com/365449/59552246-16740480-8fb7-11e9-99e4-4c8c50255a9a.png)

官方中文没有这个情况
我随机对比了一下某文件，发现github上有些英文文档也没有完全导入最新的词条

**Comment by wzy9607** [comment]
我这本地用的git工具总是把有BOM和没BOM弄混....
