### ISSUE TITLE
[BUG]词条丢失

### ISSUE THREAD

**Issue by fqqdc** [cloudwu/stellaris_cn#758]
![image](https://user-images.githubusercontent.com/365449/59556313-e3e7fd00-8ff2-11e9-8718-808635c3c887.png)

**Comment by cloudwu** [comment]
我查了一下，这些词条在 Steam\steamapps\common\Stellaris\localisation_synced 目录下。本 mod 并没有修改这些文件，理论上应该用游戏自带的。

是不是你用了别的 mod 覆盖了这些 localisation_synced 下的文件但没有更新？

**Comment by fqqdc** [comment]
我有游戏设置的是“中文”，为了使用中文命名的星系。
mod就两个，一个是这个汉化，一个是字体。

**Comment by cloudwu** [comment]
我试了一下，替换 localisation_synced 目录会影响 checksum 进而影响成就。你可以本地试试 copy 这个目录到 mod 下，修改一下看能不能正确。

**Comment by cloudwu** [comment]
另外，你可以搜索 `NAME_Grand_Dragon: "Grand Dragon"` 这个词条在不在你的硬盘上。理论上它应该在 `Steam\steamapps\common\Stellaris\localisation_synced\ship_design_names.yml` 或 `Steam\steamapps\common\Stellaris\localisation_synced\ship_design_names_SC.yml` 中。另外，还要看有没有 mod 替换 `localisation_synced\ship_design_names.yml` 或 `localisation_synced\ship_design_names_SC.yml` 文件。

**Comment by cloudwu** [comment]
![image](https://user-images.githubusercontent.com/729648/59558531-f3813900-9026-11e9-946b-8498fa197306.png)

我用控制台调出来一只 Grand Dragon ，界面上是可以显示 大龙级 的。

**Comment by fqqdc** [comment]
我直接搜索游戏目录，是有找到相关词条
![image](https://user-images.githubusercontent.com/365449/59561553-694fc980-9054-11e9-816f-34808e9e85cd.png)
但我玩的是铁人存档，没法在游戏里重现，等有时间玩下一盘再看看吧
