### ISSUE TITLE
2.4汉化不管用了

### ISSUE THREAD

**Issue by wzy9607** [cloudwu/stellaris_cn#776]
要放到replace\r_***yml才能用

**Comment by wzy9607** [comment]
魔改一下simpc.lua应该就行了

**Comment by cloudwu** [comment]
写一下新的目录结构？

**Comment by cloudwu** [comment]
我玩了一下，选了 English ，汉化是有效的。

**Comment by wzy9607** [comment]
...\english\replace\r_<original_file_name>
...\simp_chinese\replace\r_<original_file_name>

**Comment by wzy9607** [comment]
但是我这不行....

**Comment by wzy9607** [comment]
奇怪....现在又好了....可能是launcher的bug

**Comment by wzy9607** [comment]
好像重启几次launcher就好了

**Comment by wzy9607** [comment]
....还是不行，刚才出现的是官汉。

**Comment by wzy9607** [comment]
![圖片](https://user-images.githubusercontent.com/17695588/66570299-eb35a680-eb9f-11e9-9cbd-a260dc35cc81.png)

**Comment by wzy9607** [comment]
我这改成本地的也能用。奇怪。可能是别的地方出问题了？

**Comment by wzy9607** [comment]
把discriptor里`archive`那行改成`path="随便什么"`就好了。
群星的mod打包策略改了....

**Comment by cloudwu** [comment]
应该修好了。但是 steam 自动更新 mod 的机制有点迷。
