### ISSUE TITLE
更新 2.5.0

### ISSUE THREAD

**Issue by cloudwu** [cloudwu/stellaris_cn#778]
最近很忙，所以精力不够。只更新了 2.5.0 的部分，还有一点没有翻译。求 pr 。

* [ ] https://github.com/cloudwu/stellaris_cn/blob/master/cn/localisation/english/dip_messages_l_english.yml#L394-L408
* [ ] https://github.com/cloudwu/stellaris_cn/blob/master/cn/localisation/english/distant_stars_l_english.yml#L1120
* [ ] https://github.com/cloudwu/stellaris_cn/blob/master/cn/localisation/english/l_english.yml#L3551-L3559
* [ ] l_english 10523 行的新种群开场故事
* [ ] https://github.com/cloudwu/stellaris_cn/blob/master/cn/localisation/english/name_lists_l_english.yml#L306-L315

@wzy9607

**Comment by wzy9607** [comment]
我差不多翻译好了，等周末游戏里检查一下几个带图标的句子再提交上来。
