### ISSUE TITLE
2.6 更新

### ISSUE THREAD

**Issue by cloudwu** [cloudwu/stellaris_cn#783]
我已经更新了 2.6 的文本。

和以往大版本更新一样，这个阶段只修改 diff 目录，并用 script/merge.lua 这个脚本合并。暂时不要直接更新 cn 目录下的任何文件。等过一遍后，我会删掉 diff 目录。

以下是所有 diff 文件列表，用于跟踪进度。

* [x] achievements_l_english.yml.diff
* [x] ai_crisis_l_english.yml.diff
* [x] ancient_relics_events_l_english.yml.diff
* [x] ancient_relics_l_english.yml.diff
* [x] apocalypse_l_english.yml.diff
* [ ] dip_messages_l_english.yml.diff
* [ ] diplo_stances_l_english.yml.diff
* [x] distant_stars_l_english.yml.diff
* [x] events_2_l_english.yml.diff
* [x] events_3_l_english.yml.diff
* [x] events_4_l_english.yml.diff
* [x] events_5_l_english.yml.diff
* [x] events_l_english.yml.diff
* [ ] federations_l_english.yml.diff
* [x] federations_resolution_comments_l_english.yml.diff
* [ ] horizonsignal_l_english.yml.diff
* [x] l_english.yml.diff
* [x] leviathans_l_english.yml.diff
* [x] lithoids_l_english.yml.diff
* [x] marauder_l_english.yml.diff
* [ ] megacorp_l_english.yml.diff
* [x] messages_l_english.yml.diff
* [x] modifiers_2_l_english.yml.diff
* [x] modifiers_l_english.yml.diff
* [x] pop_factions_l_english.yml.diff
* [ ] prescripted_l_english.yml.diff
* [x] ship_sections_l_english.yml.diff
* [x] technology_l_english.yml.diff
* [x] traditions_l_english.yml.diff
* [ ] triggers_effects_l_english.yml.diff
* [ ] tutorial_l_english.yml.diff
* [x] utopia_ascension_l_english.yml.diff
* [x] utopia_l_english.yml.diff
* [x] utopia_megastructures_l_english.yml.diff

**Comment by wzy9607** [comment]
有大量没有内容变动的文件被错误加入了diff，如name_lists_l_english.yml.diff、observer_events_l_english.yml.diff、observer_l_english.yml.diff等。

**Comment by cloudwu** [comment]
我今天会初步整理完 l_english 。

**Comment by wzy9607** [comment]
p社紧急更新2.6.1了，官汉文本变化较大。

**Comment by cloudwu** [comment]
我今天会重新写脚本，把 2.6.1 更新的官方文本，老的我们的 2.5 的汉化文本，以及这两天我们做的修改，三者合并，然后重新提交。

注：我们确认的文本最后都打上 CHANGE 的标签，如果想保留 CN2 ，就不动；不要复制为 CHANGE。

如果想用原有的 CN 条目，复制一条改成 CHANGE 。

不要在 CN2 上做修改。

这样，脚本就可以方便的识别出那些是我们确认过的。

**Comment by cloudwu** [comment]
2.6.1 的合并工作已经完成。不过 @wzy9607 有部分修改是直接修改的 CN2 那行，我的脚本没有识别，（目前只识别了 CHANGE 行）所以会被回退。麻烦重新 review 一遍。

另外：建议 pr 不提交 merge （脚本生成）的结果，这样可以减轻 review PR 的工作。可以考虑在本地自建分支运行 merge 看效果。

**Comment by wzy9607** [comment]
暂定翻译
Galactic Community : 银河共同体
Galactic Council : 银河理事会
Diplomatic Weight : 外交话语权
Diplomacy Stance : 外交姿态

**Comment by cloudwu** [comment]
术语的话，麻烦更新一下现在已经改过的文件。比如外交话语权这个。

**Comment by cloudwu** [comment]
上面几个术语，因为新文件中出现太多了，我先统一替换掉。（直接修改的  CN2 行）
接下来这些行依旧需要人工 review 。

**Comment by wzy9607** [comment]
我这mod还是没有效果。

**Comment by cloudwu** [comment]
我在 twitter 上和 P 社官方私信讨论了这个问题，应该是启动器 bug 。尤其是同样的 mod 同时存在本地和 workshop 的容易出问题。

一般把 mod 目录清空，重新订阅，可以解决问题。

**Comment by wzy9607** [comment]
`Favor`暂时参考CK翻译成了`人情`（官汉用的外交支持），`Call in favor`暂时翻译的是`请求人情支援`，涉及文本在#796已经处理完了。

**Comment by dalu98** [comment]
对于`federation leader`的翻译貌似 @wzy9607 说的是对的。在官中下搜索了一下对应的词，似乎指的就是`联邦主席国`

<img width="1300" alt="截屏2020-03-23下午9 56 30" src="https://user-images.githubusercontent.com/25452934/77326945-7f15bc00-6d55-11ea-8cbb-6b3dc9e3a2a7.png">

**Comment by cloudwu** [comment]
我个人觉得，既然英文可以用不同的词指代一个东西，翻译一样可以灵活处理。

**Comment by dalu98** [comment]
> 我个人觉得，既然英文可以用不同的词指代一个东西，翻译一样可以灵活处理。

那不妨翻译成`联邦领导国`，跟`联邦主席国`和`联邦成员国`相对应

**Comment by wzy9607** [comment]
昨天忘说了，diff目录可以处理掉了。
