### ISSUE TITLE
3.0 校对工作

### ISSUE THREAD

**Issue by cloudwu** [cloudwu/stellaris_cn#814]
3.0 的文本已经更新。和以前一样，需要先在 diff 目录校对。

@wzy9607

**Comment by wzy9607** [comment]
3.0更新的文本真不少

**Comment by wzy9607** [comment]
## 暂译
* Planet Capacity 行星承载力
* First Contact 第一次接触 首次接触？
* Espionage 谍报
* spy 刺探（v）；间谍（n）
* Spy Network 间谍网
* Spy Power 间谍力量 间谍实力？

**Comment by cloudwu** [comment]
First Contact 在科幻小说里一般翻译成 第一次接触   https://zh.wikipedia.org/wiki/%E7%AC%AC%E4%B8%80%E6%AC%A1%E6%8E%A5%E8%A7%A6_(%E7%A7%91%E5%B9%BB)

Spy Power  我觉得 间谍实力  比较好。

**Comment by wzy9607** [comment]
那 First Contact 就沿用第一次接触。
间谍那些看看是怎么用的再决定。

DLC 加了一级军舰叫 Star-Eater ，官汉翻译成了焚天神兵...不过噬星者被 Stellar Devourer 用了得另找个词。
还有个银河共同体变成 Galactic Imperium 新内容，用帝国翻译 Imperium/Imperial 感觉容易歧异。

**Comment by cloudwu** [comment]
我觉得 Galactic Imperium 可以翻译成 银河大帝国，其首领可以称为 霸主 。
