### ISSUE TITLE
关于 3.4.5 版本

### ISSUE THREAD

**Issue by fqqdc** [cloudwu/stellaris_cn#825]
官方中文好像漏了一些词条，能否找出来先直接用英文原文填充呢？

**Comment by cloudwu** [comment]
https://github.com/cloudwu/stellaris_cn/commit/2eb72060900a6ef8b2f1994692938f0d701e7f28

我已经人肉同步了一下，似乎不是很多。最近在忙其它事情，可否花点时间按上面这个提交的差异来补充一下新增加的翻译？

**Comment by fqqdc** [comment]
megacorp_l_english.yml文件，词条：job_telepath_effect_desc:0，英文原文不存在该词条。

**Comment by fqqdc** [comment]
已经提交申请了。
megacorp_l_english.yml文件的词条：job_telepath_effect_desc:0，好像有点问题。我手动把英文原文本搬过来。
