### ISSUE TITLE
不知道是乱码还是未翻译的词条

### ISSUE THREAD

**Issue by fqqdc** [cloudwu/stellaris_cn#829]
![image](https://user-images.githubusercontent.com/365449/179194262-4e3f7106-90bf-436e-9b39-34206a519233.png)

**Comment by cloudwu** [comment]
这一条在 https://github.com/cloudwu/stellaris_cn/blob/master/cn/localisation/english/triggers_effects_l_english.yml#L1825

military 是解析 CATEGORY 这个变量出来的串。

我猜想本来应该替换成 military_NAME ，https://github.com/cloudwu/stellaris_cn/blob/master/cn/localisation/english/nemesis_intel_l_english.yml#L117 但有 bug 没有解析对。
