### ISSUE TITLE
创意工坊版本mod中文模式下翻译文本缺失

### ISSUE THREAD

**Issue by szl0834** [cloudwu/stellaris_cn#830]
我对比了l_english.yml 和 l_simp_chinese.yml, 发现后者相比前者缺少了很多行翻译文本。部分行的翻译内容也不同，感觉可能是转换的过程搞错了？
![image](https://user-images.githubusercontent.com/16066867/190874350-ce9851ad-4a22-4d43-b601-d5659f3567b7.png)

**Comment by cloudwu** [comment]
已经重新上传了一次。

**Comment by szl0834** [comment]
> 已经重新上传了一次。

感谢
