### ISSUE TITLE
diff 目录里多了好多词条，要怎么修改？

### ISSUE THREAD

**Issue by fqqdc** [cloudwu/stellaris_cn#831]
好久没做，记不得该怎么操作了。

**Comment by cloudwu** [comment]
我晚上重新整理一下。diff 应该是没删干净。

**Comment by fqqdc** [comment]
最新版本的MOD中有很多词条都还是英文，我在diff中也找到对应的词条。

**Comment by cloudwu** [comment]
diff 目录已删，我记得已经合并过了。如果还有英文的，直接改了提交 pr 即可。

**Comment by fqqdc** [comment]
以leviathans_l_english.yml为例，其中有大量的英文条目（估计有20条以上），每一个条目下都有三行注释，看起来像是脚本出了问题，直接把diff的文本直接复制过来，并没有成功替换。

**Comment by cloudwu** [comment]
@fqqdc 文本已经更新到 3.6 ，粗略合并了官方文本，还需要校对。

另外，这个版本对随机组合的名字做了更好的支持，具体见 https://github.com/cloudwu/stellaris_cn/blob/master/cn/localisation/english/name_system_l_english.yml

我认为可以多花点精力把这些名字都弄得好看一些。

**Comment by cloudwu** [comment]
> 以leviathans_l_english.yml为例，其中有大量的英文条目（估计有20条以上），每一个条目下都有三行注释，看起来像是脚本出了问题，直接把diff的文本直接复制过来，并没有成功替换。 

我想起来这是故意为之。现在的合并脚本发现条目被修改后，会保留新版本英文原文，然后把原来的英文、原来的中译、新的官方翻译都以注释的形式留在文件里。这样方便人工审校。
