### ISSUE TITLE
3.7 已更新

### ISSUE THREAD

**Issue by cloudwu** [cloudwu/stellaris_cn#833]
文本已经更新到了 3.7 。重写了合并脚本。

目前还有大约 60 条漏译的文本。@fqqdc 有空可以看看。搜索 TODO 就能找到，可以直接提交修改。

**Comment by fqqdc** [comment]
cn目录下的TODO好像已经全部翻译了，我没找到需要翻译的文本。

**Comment by cloudwu** [comment]
例如： https://github.com/cloudwu/stellaris_cn/blob/master/cn/localisation/english/first_contact_l_english.yml#L32

可以去 script 目录下跑 `lua merge.lua` 生成一个报告，看到哪些 TODO 。建议注释掉 `output(data)` 那行，只保留 `output_diff(diff)` ，因为 output 会覆盖掉已经编辑好的文本。

**Comment by fqqdc** [comment]
存在很多TODO标记的语句，但其已经翻译过了，建议进行清理。

**Comment by cloudwu** [comment]
可能脚本有 bug , 或者应该打个更特殊的 tag
