### ISSUE TITLE
更新 3.8.3

### ISSUE THREAD

**Issue by cloudwu** [cloudwu/stellaris_cn#842]
今天更新到了 3.8.3 ，这次小更新有很多文本，目前除了部分英文顺手翻译外，还有不少保留了英文词条。（没有核对新版本的官方中文）

@fqqdc 可以看看。差异可以看 https://github.com/cloudwu/stellaris_cn/commit/10c5f180daa949e9e3ab174e94d73c7db13fbfca

**Comment by fqqdc** [comment]
建议上传官方中文文本，方便对照和引用。

**Comment by cloudwu** [comment]
已经加好了。

**Comment by fqqdc** [comment]
已经根据差异补齐文本，并且提交了合并请求。建议合并后关闭当前issue。
