### ISSUE TITLE
1.4 官方中文发布

### ISSUE THREAD

**Issue by cloudwu** [cloudwu/stellaris_cn#85]
今天群星更新了 1.4 ，加入了官方中文。

可惜翻译质量还有待提高，各位同学如果在玩的过程中发现问题，还是可以继续在这里提交 pr 。我会继续维护原 Mod :)

ps. 原 Mod 现在已经更新成 1.4 官方中文文本了，老文本移到了 cn1.3 目录下。

目前暂时只修正了主界面的 "恢复点数" 为 "集结点" 。

**Comment by soarqin** [comment]
官方中文新加1.4词条的位置是在尾部，和英文版对不上，我觉得应该先整理过去，然后才好和我们之前做的1.3来对比校修

**Comment by soarqin** [comment]
另外建议老文本发一个新的MOD，给习惯老翻译的人在1.4上直接用，官方汉化校修工作，我会先用vimdiff对比一下把一些关键的词批量修掉

**Comment by cloudwu** [comment]
好，可以先整理一下和英文对应好。不过老文本需要和 1.4 的英文再搞一次合并，所以我就懒得发新的了。

维护两个 mod 也不方便，不如就一个，用词主要按老的来。

**Comment by cloudwu** [comment]
利维坦的文本，由于官中在这块偷工减料，我已经全部迁回我们自己的老文本了。
