### ISSUE TITLE
关于Curator翻译的讨论

### ISSUE THREAD

**Issue by soarqin** [cloudwu/stellaris_cn#89]
因为Curator本身没有博物馆的意思，所以我一直以来都觉得这个翻译可能不太恰当。
贴吧汉化作“策展人”，这个就更加不合适了。
分析了一下游戏中这个系列事件这个组织的作用，结合Curator的含义，个人认为翻译成“(银河)监察者”可能比较好。

**Comment by cloudwu** [comment]
没问题，可以统一改。ps. 我也不喜欢 策展人 ，意译比较好。

**Comment by Tianchenglipu** [comment]
curator可以指图书馆员，或者策展人，就是为艺术家策划展览的。有的汉化组将它直接翻译成策展人，明显是都没有查一下策展人是什么意思。
为了体现出“他们有一个很大的知识库”，我自己想的译法是“博库人”，其中我最不满意的字是“人”，因为他们不一定是人啊！

**Comment by soarqin** [comment]
Curator这个组织有两个核心特点，一是拥有丰富的知识，二是有很长的存在历史，其主旨是保护和传承这些知识。作为命名来说，最好能想一个包含两者含义的名字，我这段时间玩得不多，但是也想过几个名字，都不是很合适。
