### ISSUE TITLE
YML翻译工具(C# .NET)

### ISSUE THREAD

**Issue by inkitter** [cloudwu/stellaris_cn#92]
功能：原文与译文对照翻译，并有百度翻译API参考；新旧版文本合并；新旧版原文差异比较；简繁转换。
链接： [https://github.com/inkitter/pdx-ymltranslator/releases](https://github.com/inkitter/pdx-ymltranslator/releases)

**Comment by inkitter** [comment]
可以新建一个bat文件放在pdx-translator.exe程序文件夹里，用`mklink`来链接git的文件夹内容。运行后会自动建立` eng `和` chn ` 文件夹并且是链接到git项目的文件夹里的。
  两行`rd`会无提示地**删除**原来的` eng `和` chn `文件夹，运行前请注意。不需要的则不要把这两行放在bat文件里。
```
rd eng /s /q
rd chn /s /q
mklink /j eng "D:\git\stellaris_cn\en\localisation"
mklink /j chn "D:\git\stellaris_cn\cn\localisation"
```

**Comment by Tianchenglipu** [comment]
巧了，我的git也是在d:\git\里 =。=

**Comment by Tianchenglipu** [comment]
能不能加入一个“旧版英文文本”，然后自动将旧版和新版英文文本的差异整合进去啊 =。=这样就会更加省力了，再怎样更新版本也不怕了

**Comment by inkitter** [comment]
@Tianchenglipu 今天更新了新旧英文对比的功能，不过不知道是不是你想要的。

**Comment by soarqin** [comment]
我本地有自己python写的脚本工具，合并加排序，还能处理贴吧那种放在子目录里的带版本后缀的文本，但是因为很多代码都是针对特殊情况的，通用性一般，所以就没分享出来
