### ISSUE TITLE
有关于Corvette的译法

### ISSUE THREAD

**Issue by Tianchenglipu** [cloudwu/stellaris_cn#93]
真正的护卫舰其实是Frigate，我个人还是趋向于给Corvette另外找个名字，比如说轻型护卫舰（可以简写为轻护舰）。

其实这不是一个大问题，因为这游戏没有Frigate，但是有的mod里是有Frigate的，比如new ship classes就加了个护卫舰，所以就很逼死强迫症，玩起来分不清哪个是Corvette哪个是Frigate。

**Comment by wzy9607** [comment]
Frigate是巡防艦。

**Comment by Tianchenglipu** [comment]
谢谢，是我一知半解了

**Comment by cloudwu** [comment]
frigate 吨位更大一些，目前游戏里有提到海盗船里有。

https://github.com/cloudwu/stellaris_cn/blob/master/en/localisation/l_english.yml#L2147

之前我们自己的版本翻译为巡防舰 https://github.com/cloudwu/stellaris_cn/blob/master/cn1.3/localisation/l_english.yml#L2147

后来合并 1.4 官方译本的时候改为了护卫舰，下次 1.5 可以改回来。

**Comment by Tianchenglipu** [comment]
……我这里的pirate_destroyer被翻译成了“炮艇”，我也是服了，差点以为就是原文→_→

**Comment by Tianchenglipu** [comment]
@wzy9607  等一下，我以为你是说“台湾把Corvette叫作巡防舰是错的，台湾把Frigate叫作巡防舰”，请让我确认一下是不是这个意思，因为那句话也有可能是指“Frigate应该翻译成巡防舰”

**Comment by Tianchenglipu** [comment]
目前我收集到的情况来看，中国大陆趋向于将Frigate叫作护卫舰，Corvette叫作轻型护卫舰。而且这也符合我玩过的其他游戏的中文翻译法 -_-
