### ISSUE TITLE
有关于AI性格名的翻译的一点建议

### ISSUE THREAD

**Issue by Tianchenglipu** [cloudwu/stellaris_cn#94]
Decadent Hierarchy与Harmonious Hierarchy：这两个AI性格之中Hierarchy使用了不同的选词，推荐使用相同的选词。我个人趋向于选用“种姓国”。我自己选用的翻译是“颓败种姓国”和“和谐种姓国”。因为解释为“种姓”的话比较方便压缩成比较少的字数，“等级制度”用来作为AI性格的名字就很奇怪，“等级制度国”字数又多又好像不是很好听……
Fanatic Purifier：将Fanatic译为“狂心”，这样会听起来很丧病。
Fanatic Befrienders：将Fanatic译为“殷切”或者“激切”，殷切比较好听，而激切听起来比较激烈。但总之要体现出他们很激烈地想要和别人做朋友的话，我认为这两个词是挺好的。至于Befrienders，“亲近者”听起来太温和了，和这个AI性格不太相符，我希望换成一个激烈一点的词。这个AI性格，我自己选用的翻译是“强进作友者”，不过我的翻译经常被人说成是“不经过我的解释就看不太懂”……至于说为什么不主张把Fanatic也统一为“狂热”，因为它太具有「泛用性」，而在Fanatic的译法上作文章是个很好的体现个性的机会。

**Comment by Tianchenglipu** [comment]
顺便一提的是：
war_demand_trait_warlike:0 "好战的统治者"
war_demand_trait_expansionist:0 "偏爱扩张的君主"
这两个我觉得有点问题

还有这两个推荐和科技同步译名
war_demand_tech_galactic_ambitions:0 "称霸银河系的野心"
war_demand_tech_manifest_destiny:0 "彰显的天命"

**Comment by Tianchenglipu** [comment]
这个文件太大了，我用网页版没法编辑:-(

**Comment by cloudwu** [comment]
下周 1.5 出来可以一起调整。

ps. github 有 windows 客户端可以下载。

**Comment by Tianchenglipu** [comment]
我有下载git客户端，但是不会用→_→

**Comment by wzy9607** [comment]
推薦用GitKraken。

**Comment by Tianchenglipu** [comment]
GitKraken到底安装到哪里了啊，我不小心关了然后

**Comment by Tianchenglipu** [comment]
GitKraken我不会用，最后还是用了git-bash.exe，但是拒绝我push，因为我没有权限……但是这似乎不该发生

**Comment by cloudwu** [comment]
你应该 push 到你 fork 的自己的仓库 https://github.com/Tianchenglipu/stellaris_cn

然后去 web 上提一下 pull request 。

**Comment by Tianchenglipu** [comment]
啊哦！好久没用了都忘了这回事！
