### ISSUE TITLE
提前讨论一下Civic和Ascension Perk的译法

### ISSUE THREAD

**Issue by Tianchenglipu** [cloudwu/stellaris_cn#98]
Civic：字面含义比较接近于Civil，但显然不能直接把Civil写上去。
思路1：民○，这是从字面出发（但是已知的Civic里有一个Police State，这大概不是一个民之属性）
思路2：国○，因为国家是由人民组成的，全民的属性可以解释成一国的属性
思路3：政府○，因为Civic是代替原先的政府的机制之一，翻译成政府○比较便于游戏玩家理解
基于这些思路的可行的翻译有：国家属性，国策，政府属性，政府特性

Ascension Perk：字面含义比较接近于“更升一步后之《Perk》”。至于Perk是什么意思，字面含义好像是“额外津贴，外快”，我朋友告诉我是网游里的技能点之类。好吧，其实我并不十分确定Perk是什么意思，但是只要有字典在，我们无所畏惧。
我推荐的翻译是“入圣徽记”。因为我认为在你选择Ascension Perk以前，你早已Ascension了，而Ascension Perk是给你的奖励，所以应该作“Ascension后，我所取得的Perk”解，而“在这以前我一直迷途，自从点了Ascension Perk以后，我就Ascension了”则是个错误理解。
至于“入圣”和“徽记”是否可以替换成其他词语，希望大家能讨论一下。

**Comment by Tianchenglipu** [comment]
还有3天就1.5了，激动难耐！

**Comment by cloudwu** [comment]
perk 是游戏中常见的词 , 比如辐射系列里的 perk 系统就很著名。
https://en.wikipedia.org/wiki/Experience_point#Perks  它大概指 a bonus which gives a video game character a special ability

国内网游语境一般指天赋技能。

**Comment by Tianchenglipu** [comment]
玩的游戏少让你笑话了=。=但总之意思我理解了

**Comment by Tianchenglipu** [comment]
入圣我朋友说听起来好似修仙，但我没觉得
而徽记其实我也不是很满意，其实选用徽记是为了说明“这是一个贵重的东西，你可要好好珍惜哦！”，但是没有成功地说明“这个东西能给你巨大的加成”
我再想想能有什么词能不落地概括

**Comment by Tianchenglipu** [comment]
我的脑壳里：
“这是一个贵重的不可多得的东西”＋“这是一个游戏里的技能点”＝“徽”
锁定不到其他的词语了，你有什么好主意吗……

**Comment by Tianchenglipu** [comment]
突然想到civic也许可以叫作“人文”？

**Comment by Tianchenglipu** [comment]
1.5可能有官方中文，steam上有官方的中文介绍，将Ascension Perk翻译成了上升点数

```
上升点数:
收集团结点数，接受传统，以解锁能够以独特方式定制自己帝国的上升点数。遵循三条上升路径中的其中一条，实现生物主宰，在共同进化中放弃自己的生物形式，或通过超越来解锁自己种族的全部灵能潜力。
```

这个文段感觉就像是机翻+润色的结果，可能这次的官方汉化还是不会有什么大起色

**Comment by cloudwu** [comment]
perk 在 fallout 里似乎翻译成 特技 http://zh.fallout.wikia.com/wiki/%E7%89%B9%E6%8A%80?varient=zh_cn

**Comment by Tianchenglipu** [comment]
但是特技是一个人的属性，Ascension Perk是整个国家的属性

**Comment by cloudwu** [comment]
perk 指的是一种额外能力，不是属性。

**Comment by Tianchenglipu** [comment]
但是特技是一个人的，Ascension Perk是整个国家的

**Comment by Tianchenglipu** [comment]
我希望翻译用词能体现「这是一个象征着我们的极高境界的来之不易的东西」。
特技听起来很像网游啊，相比之下技术都会更好的感觉。


想像一下下面的文本都是在游戏中的：

```
入圣造诣
- 建造戴森球＆环形世界＆科研枢纽＆监探阵列
- 建造轨道空间站
```

```
入圣之徽
- 建造戴森球＆环形世界＆科研枢纽＆监探阵列
- 建造轨道空间站
```

```
入圣之技
- 建造戴森球＆环形世界＆科研枢纽＆监探阵列
- 建造轨道空间站
```

……好像都没什么大问题？

**Comment by cloudwu** [comment]
Ascension 在台湾造了一个专门的词翻译，叫做 扬升。比如：http://www.elook.com.tw/sprit/sprit_03.htm

**Comment by Tianchenglipu** [comment]
可是此网站的接下来的文本是不是很……

```
"揚昇"提供人們找到身心健康的關鍵，超越個人極限及成癮性行為，活化更多的DNA，
讓你在生活中體驗到更多的愛與喜悅，減少壓力，實現個人人生使命，轉化生命的批判，
找到生命"永恆"答案。
```

**Comment by cloudwu** [comment]
科幻小说深渊上的火里翻译成飞升，语境和群星里一样。群星本来就是玩科幻梗。

**Comment by Tianchenglipu** [comment]
```
飞升特技
- 建造戴森球＆环形世界＆科研枢纽＆监探阵列
- 建造环轨居所
```

```
扬升特技
- 建造戴森球＆环形世界＆科研枢纽＆监探阵列
- 建造环轨居所
```

**Comment by Tianchenglipu** [comment]
游戏图像上看来Ascension Perk是论槽的，合计8槽，从下拉菜单中将Ascension Perk的卡片拖入槽中解锁。如果叫OO点数，我总觉得很违背直觉。

**Comment by Tianchenglipu** [comment]
优越之证
卓绝之证
卓越之证
这样的风格呢？

**Comment by cloudwu** [comment]
扬升特技 这个感觉也不算违和啊

**Comment by Tianchenglipu** [comment]
可是扬一般都是动词啊……扬升听起来像是将某种东西以某种力量弄到飘起来，类似于给气球充气

**Comment by Tianchenglipu** [comment]
我理解的是这样的：
`飞升特技 = flying-up ability`
`扬升特技 = flail-myself-up ability`
`飞升点数 = flying-up points`
`扬升特技 = flail-myself-up points`
`入圣之证/徽 = medal/emblem of transcendent`

**Comment by cloudwu** [comment]
sperk = 特典呢？

**Comment by Tianchenglipu** [comment]
听起来不错

`飞升特典 = special reward of flown-up`
`扬升特典 = special reward of flailed-myself-up`
`入圣特典 = special reward of became-transcendent-status`

听起来非常有感觉

**Comment by Tianchenglipu** [comment]
没没没没有官中！让我们继续汉化！

**Comment by cloudwu** [comment]
Civic 我主张采用 公民性

**Comment by Tianchenglipu** [comment]
可是贵族精英听起来不像是一个公民性啊。有不少civic并不是形容公民的。而且蜂群思维的那些civic就更不公民了。

（告诉你一个秘密，瑞典蠢驴说，对蜂群思维而言影响力是蜂群思维对族群的控制力）

而且公民性，一个二字词和一个一字词组合，听起来有点怪。类似于听到把国情叫作国家情，把政策叫作政府策这些说法的感觉。公民属性，或者民性，这样听起来我觉得顺耳一点。

**Comment by cloudwu** [comment]
首先 Civics 是一个专有词， 并不是 Civic 的复数。 https://en.wikipedia.org/wiki/Civics
它是指 study of the theoretical and political and practical aspects of citizenship 。

中文没有特别的对应词，按中文维基的用语是 公民教育 https://zh.wikipedia.org/wiki/%E5%85%AC%E6%B0%91%E6%95%99%E8%82%B2

日文直接翻译为公民，特指一种政治学科。

国民性 民族性 公民性 挺正常的词啊。

**Comment by Tianchenglipu** [comment]
要是三选一的话，我认为民族性比较好接受，因为蜂群意识也可以讲民族――虽然是一个光杆司令？

**Comment by cloudwu** [comment]
公民性不是我造的词，和民族性不同。 http://theory.people.com.cn/BIG5/n/2012/1024/c112851-19370126.html

**Comment by Tianchenglipu** [comment]
我在手机上看不了那些链接=。=

**Comment by cloudwu** [comment]
不过公民性一般是对 citizenship 的翻译。

**Comment by cloudwu** [comment]
http://202.120.85.33/Jweb_zgcsyj/CN/abstract/abstract114.shtml  公民性与基层治理:基于两个上海社区的定量研究 （Civicness and Local Governance: A Quantitative Research on Two Shanghai Neighborhoods）

**Comment by Tianchenglipu** [comment]
还有没有字数是偶数的译法，最好是2字的=。=三个汉字码上去好难受啊，是因为我是强迫症吗

要是实在没有的话公民性也行吧

**Comment by Tianchenglipu** [comment]
贴吧汉化组把civic翻译成了“国是”，这和之前的虚境一样是上层人员钦定的结果 =。=

**Comment by cloudwu** [comment]
国是也挺好的，其实日本人也这么翻译的。 https://simulationian.com/2017/02/stellaris-dd20170223/

**Comment by Tianchenglipu** [comment]
咳咳，a wall is blocking the page!

**Comment by cloudwu** [comment]
https://simulationian.com/2017/02/stellaris-dd20170223/  「Stellaris」開発日記#62――政府・国是・集合意識

**Comment by Tianchenglipu** [comment]
谷歌翻译 JP → CH：
国是 → 国策

谷歌翻译 JP → EN：
国是 → national policy

谷歌翻译 自动检测语言：
国是 ： 检测到日语

还觉得“国是”好吗

**Comment by Tianchenglipu** [comment]
顺便一提的是，我开谷歌翻译纯粹是想看一下“国是”在日语怎么读，因为我的直觉告诉我读kokuzei，但是输入法打不出来，然后谷歌翻译告诉我是kokuze =。=

结果谁知道发现国是果然是一次日语词。

虽然汉语已经夹杂了许多日语词，但是“国是”暂时还没有和“哲学”这些词一样盛行开来。

**Comment by cloudwu** [comment]
国是 的 本源是说 国家认为正确的事情，  是 是非 的是。

日本保留了大量古汉语的词，并非日语词。

我不喜欢用现代汉语中的生僻词，毕竟是游戏。

**Comment by Tianchenglipu** [comment]
那国是不就是governing ethic。

我最开始还以为国是的意思是「这个国家的存在面貌」。我不知道怎样表达比较好。

既然国是的意思是「这个国家认为正确的事情」，那我坚决反对啊。

**Comment by Tianchenglipu** [comment]
首先，生僻是一方面，这已经足够否决此翻译。然后，这个词的含义和civics不太一样。

也许你可以找来一大堆同义词，比如政策、国策，来指代游戏中的不同概念，只求字面上不混淆，但这种翻译方法我是不赞同的，否则就和日语一样全部用片假名写不就好了，为什么还要翻译。

这次国是的含义直接和 governing ethic 撞上了，所以绝对不能用。

**Comment by cloudwu** [comment]
日本人曾经比较擅长从中国古籍中找词，古词新用。比如社会、经济 ，为了表达西方的词意，其实和古汉语的意思差得比较远。只是用多了就掰过来了。

作为游戏翻译，还是不发明词的好。

**Comment by Tianchenglipu** [comment]
我倒觉得用一个超生僻词和自己发明词语没有区别。举例来说，鲁迅先生造的猹字，对我们来说，和一个没见过的生僻字，并没有区别。

**Comment by cloudwu** [comment]
我的意思就是说，国是 == civics 是在发明词。

**Comment by Tianchenglipu** [comment]
好吧，我懂了。
